module Sam
  module Models
    module Store
      type order_retrieve_params = {  } & Sam::request_parameters

      class OrderRetrieveParams < Sam::BaseModel
        extend Sam::RequestParameters::Converter
        include Sam::RequestParameters

        def initialize:
          (request_options: Sam::request_opts) -> void
          | (
            ?Sam::Models::Store::order_retrieve_params | Sam::BaseModel data
          ) -> void

        def to_h: -> Sam::Models::Store::order_retrieve_params
      end
    end
  end
end
