module Sam
  module Models
    module Store
      type order_delete_params = {  } & Sam::request_parameters

      class OrderDeleteParams < Sam::BaseModel
        extend Sam::RequestParameters::Converter
        include Sam::RequestParameters

        def initialize:
          (request_options: Sam::request_opts) -> void
          | (
            ?Sam::Models::Store::order_delete_params | Sam::BaseModel data
          ) -> void

        def to_h: -> Sam::Models::Store::order_delete_params
      end
    end
  end
end
