module Sam
  module Resources
    class MessagesBetaTrue
      def create: (
        max_tokens: Integer,
        messages: ::Array[Sam::MessagesBetaTrueCreateParams::Message],
        model: String,
        ?metadata: Sam::MessagesBetaTrueCreateParams::Metadata,
        ?stop_sequences: ::Array[String],
        ?stream: bool,
        ?system_: Sam::Models::MessagesBetaTrueCreateParams::system_,
        ?temperature: Float,
        ?thinking: Sam::Models::MessagesBetaTrueCreateParams::thinking,
        ?tool_choice: Sam::Models::MessagesBetaTrueCreateParams::tool_choice,
        ?tools: ::Array[Sam::Models::MessagesBetaTrueCreateParams::tool],
        ?top_k: Integer,
        ?top_p: Float,
        ?anthropic_beta: ::Array[String],
        ?anthropic_version: String,
        ?x_api_key: String,
        ?request_options: Sam::request_opts
      ) -> Sam::Models::MessagesBetaTrueCreateResponse

      def initialize: (client: Sam::Client) -> void
    end
  end
end
