module Sam
  module Resources
    class ModelsBetaTrue
      def list:
        (
          ?Sam::Models::ModelsBetaTrueListParams | ::Hash[Symbol, top] params
        ) -> Sam::Models::ModelsBetaTrueListResponse
        | (
          ?after_id: String,
          ?before_id: String,
          ?limit: Integer,
          ?anthropic_version: String,
          ?x_api_key: String,
          ?request_options: Sam::request_opts
        ) -> Sam::Models::ModelsBetaTrueListResponse

      def initialize: (client: Sam::Client) -> void
    end
  end
end
