module Sam
  module Resources
    class User
      def create:
        (
          ?Sam::Models::UserCreateParams | ::Hash[Symbol, top] params
        ) -> Sam::Models::UserAPI
        | (
          id: Integer,
          email: String,
          first_name: String,
          last_name: String,
          password: String,
          phone: String,
          username: String,
          user_status: Integer,
          request_options: Sam::request_opts
        ) -> Sam::Models::UserAPI

      def retrieve:
        (
          String username,
          ?Sam::Models::UserRetrieveParams | ::Hash[Symbol, top] params
        ) -> Sam::Models::UserAPI
        | (
          String username,
          request_options: Sam::request_opts
        ) -> Sam::Models::UserAPI

      def update:
        (
          String path_username,
          ?Sam::Models::UserUpdateParams | ::Hash[Symbol, top] params
        ) -> nil
        | (
          String path_username,
          id: Integer,
          email: String,
          first_name: String,
          last_name: String,
          password: String,
          phone: String,
          body_username: String,
          user_status: Integer,
          request_options: Sam::request_opts
        ) -> nil

      def delete:
        (
          String username,
          ?Sam::Models::UserDeleteParams | ::Hash[Symbol, top] params
        ) -> nil
        | (String username, request_options: Sam::request_opts) -> nil

      def create_list:
        (
          Sam::Models::UserCreateListParams | ::Hash[Symbol, top] params
        ) -> Sam::Models::UserAPI
        | (
          body: ::Array[Sam::Models::UserAPI],
          request_options: Sam::request_opts
        ) -> Sam::Models::UserAPI

      def login:
        (?Sam::Models::UserLoginParams | ::Hash[Symbol, top] params) -> String
        | (
          password: String,
          username: String,
          request_options: Sam::request_opts
        ) -> String

      def logout:
        (?Sam::Models::UserLogoutParams | ::Hash[Symbol, top] params) -> nil
        | (request_options: Sam::request_opts) -> nil

      def initialize: (client: Sam::Client) -> void
    end
  end
end
