module Sam
  module Models
    module Messages
      type batches_beta_true_list_response =
        {
          data: ::Array[Sam::Models::Messages::BatchesBetaTrueListResponse::Data],
          first_id: String?,
          has_more: bool,
          last_id: String?
        }

      class BatchesBetaTrueListResponse < Sam::Internal::Type::BaseModel
        attr_accessor data: ::Array[Sam::Models::Messages::BatchesBetaTrueListResponse::Data]

        attr_accessor first_id: String?

        attr_accessor has_more: bool

        attr_accessor last_id: String?

        def initialize: (
          data: ::Array[Sam::Models::Messages::BatchesBetaTrueListResponse::Data],
          first_id: String?,
          has_more: bool,
          last_id: String?
        ) -> void

        def to_hash: -> Sam::Models::Messages::batches_beta_true_list_response

        type data =
          {
            id: String,
            archived_at: Time?,
            cancel_initiated_at: Time?,
            created_at: Time,
            ended_at: Time?,
            expires_at: Time,
            processing_status: Sam::Models::Messages::BatchesBetaTrueListResponse::Data::processing_status,
            request_counts: Sam::Models::Messages::BatchesBetaTrueListResponse::Data::RequestCounts,
            results_url: String?,
            type: :message_batch
          }

        class Data < Sam::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor archived_at: Time?

          attr_accessor cancel_initiated_at: Time?

          attr_accessor created_at: Time

          attr_accessor ended_at: Time?

          attr_accessor expires_at: Time

          attr_accessor processing_status: Sam::Models::Messages::BatchesBetaTrueListResponse::Data::processing_status

          attr_accessor request_counts: Sam::Models::Messages::BatchesBetaTrueListResponse::Data::RequestCounts

          attr_accessor results_url: String?

          attr_accessor type: :message_batch

          def initialize: (
            id: String,
            archived_at: Time?,
            cancel_initiated_at: Time?,
            created_at: Time,
            ended_at: Time?,
            expires_at: Time,
            processing_status: Sam::Models::Messages::BatchesBetaTrueListResponse::Data::processing_status,
            request_counts: Sam::Models::Messages::BatchesBetaTrueListResponse::Data::RequestCounts,
            results_url: String?,
            ?type: :message_batch
          ) -> void

          def to_hash: -> Sam::Models::Messages::BatchesBetaTrueListResponse::data

          type processing_status = :in_progress | :canceling | :ended

          module ProcessingStatus
            extend Sam::Internal::Type::Enum

            IN_PROGRESS: :in_progress
            CANCELING: :canceling
            ENDED: :ended

            def self?.values: -> ::Array[Sam::Models::Messages::BatchesBetaTrueListResponse::Data::processing_status]
          end

          type request_counts =
            {
              canceled: Integer,
              errored: Integer,
              expired: Integer,
              processing: Integer,
              succeeded: Integer
            }

          class RequestCounts < Sam::Internal::Type::BaseModel
            attr_accessor canceled: Integer

            attr_accessor errored: Integer

            attr_accessor expired: Integer

            attr_accessor processing: Integer

            attr_accessor succeeded: Integer

            def initialize: (
              canceled: Integer,
              errored: Integer,
              expired: Integer,
              processing: Integer,
              succeeded: Integer
            ) -> void

            def to_hash: -> Sam::Models::Messages::BatchesBetaTrueListResponse::Data::request_counts
          end
        end
      end
    end
  end
end
