module Sam
  module Models
    type message_count_tokens_params =
      {
        messages: ::Array[Sam::Models::MessageCountTokensParams::Message],
        model: String,
        system_: Sam::Models::MessageCountTokensParams::system_,
        thinking: Sam::Models::MessageCountTokensParams::thinking,
        tool_choice: Sam::Models::MessageCountTokensParams::tool_choice,
        tools: ::Array[Sam::Models::MessageCountTokensParams::tool],
        anthropic_beta: ::Array[String],
        anthropic_version: String,
        x_api_key: String
      }
      & Sam::Internal::Type::request_parameters

    class MessageCountTokensParams < Sam::BaseModel
      extend Sam::Internal::Type::RequestParameters::Converter
      include Sam::Internal::Type::RequestParameters

      attr_accessor messages: ::Array[Sam::Models::MessageCountTokensParams::Message]

      attr_accessor model: String

      attr_reader system_: Sam::Models::MessageCountTokensParams::system_?

      def system_=: (
        Sam::Models::MessageCountTokensParams::system_
      ) -> Sam::Models::MessageCountTokensParams::system_

      attr_reader thinking: Sam::Models::MessageCountTokensParams::thinking?

      def thinking=: (
        Sam::Models::MessageCountTokensParams::thinking
      ) -> Sam::Models::MessageCountTokensParams::thinking

      attr_reader tool_choice: Sam::Models::MessageCountTokensParams::tool_choice?

      def tool_choice=: (
        Sam::Models::MessageCountTokensParams::tool_choice
      ) -> Sam::Models::MessageCountTokensParams::tool_choice

      attr_reader tools: ::Array[Sam::Models::MessageCountTokensParams::tool]?

      def tools=: (
        ::Array[Sam::Models::MessageCountTokensParams::tool]
      ) -> ::Array[Sam::Models::MessageCountTokensParams::tool]

      attr_reader anthropic_beta: ::Array[String]?

      def anthropic_beta=: (::Array[String]) -> ::Array[String]

      attr_reader anthropic_version: String?

      def anthropic_version=: (String) -> String

      attr_reader x_api_key: String?

      def x_api_key=: (String) -> String

      def initialize: (
        messages: ::Array[Sam::Models::MessageCountTokensParams::Message],
        model: String,
        ?system_: Sam::Models::MessageCountTokensParams::system_,
        ?thinking: Sam::Models::MessageCountTokensParams::thinking,
        ?tool_choice: Sam::Models::MessageCountTokensParams::tool_choice,
        ?tools: ::Array[Sam::Models::MessageCountTokensParams::tool],
        ?anthropic_beta: ::Array[String],
        ?anthropic_version: String,
        ?x_api_key: String,
        ?request_options: Sam::request_opts
      ) -> void

      def to_hash: -> Sam::Models::message_count_tokens_params

      type message =
        {
          content: Sam::Models::MessageCountTokensParams::Message::content,
          role: Sam::Models::MessageCountTokensParams::Message::role
        }

      class Message < Sam::BaseModel
        attr_accessor content: Sam::Models::MessageCountTokensParams::Message::content

        attr_accessor role: Sam::Models::MessageCountTokensParams::Message::role

        def initialize: (
          content: Sam::Models::MessageCountTokensParams::Message::content,
          role: Sam::Models::MessageCountTokensParams::Message::role
        ) -> void

        def to_hash: -> Sam::Models::MessageCountTokensParams::message

        type content =
          String
          | ::Array[Sam::Models::MessageCountTokensParams::Message::Content::union_member1]

        module Content
          extend Sam::Union

          type union_member1 =
            Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestTextBlock
            | Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestImageBlock
            | Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestToolUseBlock
            | Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestToolResultBlock
            | Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock
            | Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestThinkingBlock
            | Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestRedactedThinkingBlock

          module UnionMember1
            extend Sam::Union

            type request_text_block =
              {
                text: String,
                type: :text,
                cache_control: Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestTextBlock::CacheControl?,
                citations: ::Array[Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestTextBlock::citation]?
              }

            class RequestTextBlock < Sam::BaseModel
              attr_accessor text: String

              attr_accessor type: :text

              attr_accessor cache_control: Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestTextBlock::CacheControl?

              attr_accessor citations: ::Array[Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestTextBlock::citation]?

              def initialize: (
                text: String,
                ?cache_control: Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestTextBlock::CacheControl?,
                ?citations: ::Array[Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestTextBlock::citation]?,
                ?type: :text
              ) -> void

              def to_hash: -> Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::request_text_block

              type cache_control = { type: :ephemeral }

              class CacheControl < Sam::BaseModel
                attr_accessor type: :ephemeral

                def initialize: (?type: :ephemeral) -> void

                def to_hash: -> Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestTextBlock::cache_control
              end

              type citation =
                Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestTextBlock::Citation::RequestCharLocationCitation
                | Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestTextBlock::Citation::RequestPageLocationCitation
                | Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestTextBlock::Citation::RequestContentBlockLocationCitation

              module Citation
                extend Sam::Union

                type request_char_location_citation =
                  {
                    cited_text: String,
                    document_index: Integer,
                    document_title: String?,
                    end_char_index: Integer,
                    start_char_index: Integer,
                    type: :char_location
                  }

                class RequestCharLocationCitation < Sam::BaseModel
                  attr_accessor cited_text: String

                  attr_accessor document_index: Integer

                  attr_accessor document_title: String?

                  attr_accessor end_char_index: Integer

                  attr_accessor start_char_index: Integer

                  attr_accessor type: :char_location

                  def initialize: (
                    cited_text: String,
                    document_index: Integer,
                    document_title: String?,
                    end_char_index: Integer,
                    start_char_index: Integer,
                    ?type: :char_location
                  ) -> void

                  def to_hash: -> Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestTextBlock::Citation::request_char_location_citation
                end

                type request_page_location_citation =
                  {
                    cited_text: String,
                    document_index: Integer,
                    document_title: String?,
                    end_page_number: Integer,
                    start_page_number: Integer,
                    type: :page_location
                  }

                class RequestPageLocationCitation < Sam::BaseModel
                  attr_accessor cited_text: String

                  attr_accessor document_index: Integer

                  attr_accessor document_title: String?

                  attr_accessor end_page_number: Integer

                  attr_accessor start_page_number: Integer

                  attr_accessor type: :page_location

                  def initialize: (
                    cited_text: String,
                    document_index: Integer,
                    document_title: String?,
                    end_page_number: Integer,
                    start_page_number: Integer,
                    ?type: :page_location
                  ) -> void

                  def to_hash: -> Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestTextBlock::Citation::request_page_location_citation
                end

                type request_content_block_location_citation =
                  {
                    cited_text: String,
                    document_index: Integer,
                    document_title: String?,
                    end_block_index: Integer,
                    start_block_index: Integer,
                    type: :content_block_location
                  }

                class RequestContentBlockLocationCitation < Sam::BaseModel
                  attr_accessor cited_text: String

                  attr_accessor document_index: Integer

                  attr_accessor document_title: String?

                  attr_accessor end_block_index: Integer

                  attr_accessor start_block_index: Integer

                  attr_accessor type: :content_block_location

                  def initialize: (
                    cited_text: String,
                    document_index: Integer,
                    document_title: String?,
                    end_block_index: Integer,
                    start_block_index: Integer,
                    ?type: :content_block_location
                  ) -> void

                  def to_hash: -> Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestTextBlock::Citation::request_content_block_location_citation
                end

                def self?.variants: -> [Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestTextBlock::Citation::RequestCharLocationCitation, Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestTextBlock::Citation::RequestPageLocationCitation, Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestTextBlock::Citation::RequestContentBlockLocationCitation]
              end
            end

            type request_image_block =
              {
                source: Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestImageBlock::source,
                type: :image,
                cache_control: Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestImageBlock::CacheControl?
              }

            class RequestImageBlock < Sam::BaseModel
              attr_accessor source: Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestImageBlock::source

              attr_accessor type: :image

              attr_accessor cache_control: Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestImageBlock::CacheControl?

              def initialize: (
                source: Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestImageBlock::source,
                ?cache_control: Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestImageBlock::CacheControl?,
                ?type: :image
              ) -> void

              def to_hash: -> Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::request_image_block

              type source =
                Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestImageBlock::Source::Base64ImageSource
                | Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestImageBlock::Source::URLImageSource

              module Source
                extend Sam::Union

                type base64_image_source =
                  {
                    data: String,
                    media_type: Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestImageBlock::Source::Base64ImageSource::media_type,
                    type: :base64
                  }

                class Base64ImageSource < Sam::BaseModel
                  attr_accessor data: String

                  attr_accessor media_type: Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestImageBlock::Source::Base64ImageSource::media_type

                  attr_accessor type: :base64

                  def initialize: (
                    data: String,
                    media_type: Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestImageBlock::Source::Base64ImageSource::media_type,
                    ?type: :base64
                  ) -> void

                  def to_hash: -> Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestImageBlock::Source::base64_image_source

                  type media_type =
                    :"image/jpeg" | :"image/png" | :"image/gif" | :"image/webp"

                  module MediaType
                    extend Sam::Enum

                    IMAGE_JPEG: :"image/jpeg"
                    IMAGE_PNG: :"image/png"
                    IMAGE_GIF: :"image/gif"
                    IMAGE_WEBP: :"image/webp"

                    def self?.values: -> ::Array[Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestImageBlock::Source::Base64ImageSource::media_type]
                  end
                end

                type url_image_source = { type: :url, url: String }

                class URLImageSource < Sam::BaseModel
                  attr_accessor type: :url

                  attr_accessor url: String

                  def initialize: (url: String, ?type: :url) -> void

                  def to_hash: -> Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestImageBlock::Source::url_image_source
                end

                def self?.variants: -> [Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestImageBlock::Source::Base64ImageSource, Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestImageBlock::Source::URLImageSource]
              end

              type cache_control = { type: :ephemeral }

              class CacheControl < Sam::BaseModel
                attr_accessor type: :ephemeral

                def initialize: (?type: :ephemeral) -> void

                def to_hash: -> Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestImageBlock::cache_control
              end
            end

            type request_tool_use_block =
              {
                id: String,
                input: top,
                name: String,
                type: :tool_use,
                cache_control: Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestToolUseBlock::CacheControl?
              }

            class RequestToolUseBlock < Sam::BaseModel
              attr_accessor id: String

              attr_accessor input: top

              attr_accessor name: String

              attr_accessor type: :tool_use

              attr_accessor cache_control: Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestToolUseBlock::CacheControl?

              def initialize: (
                id: String,
                input: top,
                name: String,
                ?cache_control: Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestToolUseBlock::CacheControl?,
                ?type: :tool_use
              ) -> void

              def to_hash: -> Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::request_tool_use_block

              type cache_control = { type: :ephemeral }

              class CacheControl < Sam::BaseModel
                attr_accessor type: :ephemeral

                def initialize: (?type: :ephemeral) -> void

                def to_hash: -> Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestToolUseBlock::cache_control
              end
            end

            type request_tool_result_block =
              {
                tool_use_id: String,
                type: :tool_result,
                cache_control: Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestToolResultBlock::CacheControl?,
                content: Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestToolResultBlock::content,
                is_error: bool
              }

            class RequestToolResultBlock < Sam::BaseModel
              attr_accessor tool_use_id: String

              attr_accessor type: :tool_result

              attr_accessor cache_control: Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestToolResultBlock::CacheControl?

              attr_reader content: Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestToolResultBlock::content?

              def content=: (
                Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestToolResultBlock::content
              ) -> Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestToolResultBlock::content

              attr_reader is_error: bool?

              def is_error=: (bool) -> bool

              def initialize: (
                tool_use_id: String,
                ?cache_control: Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestToolResultBlock::CacheControl?,
                ?content: Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestToolResultBlock::content,
                ?is_error: bool,
                ?type: :tool_result
              ) -> void

              def to_hash: -> Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::request_tool_result_block

              type cache_control = { type: :ephemeral }

              class CacheControl < Sam::BaseModel
                attr_accessor type: :ephemeral

                def initialize: (?type: :ephemeral) -> void

                def to_hash: -> Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestToolResultBlock::cache_control
              end

              type content =
                String
                | ::Array[Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestToolResultBlock::Content::union_member1]

              module Content
                extend Sam::Union

                type union_member1 =
                  Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestToolResultBlock::Content::UnionMember1::RequestTextBlock
                  | Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestToolResultBlock::Content::UnionMember1::RequestImageBlock

                module UnionMember1
                  extend Sam::Union

                  type request_text_block =
                    {
                      text: String,
                      type: :text,
                      cache_control: Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestToolResultBlock::Content::UnionMember1::RequestTextBlock::CacheControl?,
                      citations: ::Array[Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestToolResultBlock::Content::UnionMember1::RequestTextBlock::citation]?
                    }

                  class RequestTextBlock < Sam::BaseModel
                    attr_accessor text: String

                    attr_accessor type: :text

                    attr_accessor cache_control: Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestToolResultBlock::Content::UnionMember1::RequestTextBlock::CacheControl?

                    attr_accessor citations: ::Array[Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestToolResultBlock::Content::UnionMember1::RequestTextBlock::citation]?

                    def initialize: (
                      text: String,
                      ?cache_control: Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestToolResultBlock::Content::UnionMember1::RequestTextBlock::CacheControl?,
                      ?citations: ::Array[Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestToolResultBlock::Content::UnionMember1::RequestTextBlock::citation]?,
                      ?type: :text
                    ) -> void

                    def to_hash: -> Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestToolResultBlock::Content::UnionMember1::request_text_block

                    type cache_control = { type: :ephemeral }

                    class CacheControl < Sam::BaseModel
                      attr_accessor type: :ephemeral

                      def initialize: (?type: :ephemeral) -> void

                      def to_hash: -> Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestToolResultBlock::Content::UnionMember1::RequestTextBlock::cache_control
                    end

                    type citation =
                      Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestToolResultBlock::Content::UnionMember1::RequestTextBlock::Citation::RequestCharLocationCitation
                      | Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestToolResultBlock::Content::UnionMember1::RequestTextBlock::Citation::RequestPageLocationCitation
                      | Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestToolResultBlock::Content::UnionMember1::RequestTextBlock::Citation::RequestContentBlockLocationCitation

                    module Citation
                      extend Sam::Union

                      type request_char_location_citation =
                        {
                          cited_text: String,
                          document_index: Integer,
                          document_title: String?,
                          end_char_index: Integer,
                          start_char_index: Integer,
                          type: :char_location
                        }

                      class RequestCharLocationCitation < Sam::BaseModel
                        attr_accessor cited_text: String

                        attr_accessor document_index: Integer

                        attr_accessor document_title: String?

                        attr_accessor end_char_index: Integer

                        attr_accessor start_char_index: Integer

                        attr_accessor type: :char_location

                        def initialize: (
                          cited_text: String,
                          document_index: Integer,
                          document_title: String?,
                          end_char_index: Integer,
                          start_char_index: Integer,
                          ?type: :char_location
                        ) -> void

                        def to_hash: -> Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestToolResultBlock::Content::UnionMember1::RequestTextBlock::Citation::request_char_location_citation
                      end

                      type request_page_location_citation =
                        {
                          cited_text: String,
                          document_index: Integer,
                          document_title: String?,
                          end_page_number: Integer,
                          start_page_number: Integer,
                          type: :page_location
                        }

                      class RequestPageLocationCitation < Sam::BaseModel
                        attr_accessor cited_text: String

                        attr_accessor document_index: Integer

                        attr_accessor document_title: String?

                        attr_accessor end_page_number: Integer

                        attr_accessor start_page_number: Integer

                        attr_accessor type: :page_location

                        def initialize: (
                          cited_text: String,
                          document_index: Integer,
                          document_title: String?,
                          end_page_number: Integer,
                          start_page_number: Integer,
                          ?type: :page_location
                        ) -> void

                        def to_hash: -> Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestToolResultBlock::Content::UnionMember1::RequestTextBlock::Citation::request_page_location_citation
                      end

                      type request_content_block_location_citation =
                        {
                          cited_text: String,
                          document_index: Integer,
                          document_title: String?,
                          end_block_index: Integer,
                          start_block_index: Integer,
                          type: :content_block_location
                        }

                      class RequestContentBlockLocationCitation < Sam::BaseModel
                        attr_accessor cited_text: String

                        attr_accessor document_index: Integer

                        attr_accessor document_title: String?

                        attr_accessor end_block_index: Integer

                        attr_accessor start_block_index: Integer

                        attr_accessor type: :content_block_location

                        def initialize: (
                          cited_text: String,
                          document_index: Integer,
                          document_title: String?,
                          end_block_index: Integer,
                          start_block_index: Integer,
                          ?type: :content_block_location
                        ) -> void

                        def to_hash: -> Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestToolResultBlock::Content::UnionMember1::RequestTextBlock::Citation::request_content_block_location_citation
                      end

                      def self?.variants: -> [Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestToolResultBlock::Content::UnionMember1::RequestTextBlock::Citation::RequestCharLocationCitation, Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestToolResultBlock::Content::UnionMember1::RequestTextBlock::Citation::RequestPageLocationCitation, Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestToolResultBlock::Content::UnionMember1::RequestTextBlock::Citation::RequestContentBlockLocationCitation]
                    end
                  end

                  type request_image_block =
                    {
                      source: Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestToolResultBlock::Content::UnionMember1::RequestImageBlock::source,
                      type: :image,
                      cache_control: Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestToolResultBlock::Content::UnionMember1::RequestImageBlock::CacheControl?
                    }

                  class RequestImageBlock < Sam::BaseModel
                    attr_accessor source: Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestToolResultBlock::Content::UnionMember1::RequestImageBlock::source

                    attr_accessor type: :image

                    attr_accessor cache_control: Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestToolResultBlock::Content::UnionMember1::RequestImageBlock::CacheControl?

                    def initialize: (
                      source: Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestToolResultBlock::Content::UnionMember1::RequestImageBlock::source,
                      ?cache_control: Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestToolResultBlock::Content::UnionMember1::RequestImageBlock::CacheControl?,
                      ?type: :image
                    ) -> void

                    def to_hash: -> Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestToolResultBlock::Content::UnionMember1::request_image_block

                    type source =
                      Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestToolResultBlock::Content::UnionMember1::RequestImageBlock::Source::Base64ImageSource
                      | Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestToolResultBlock::Content::UnionMember1::RequestImageBlock::Source::URLImageSource

                    module Source
                      extend Sam::Union

                      type base64_image_source =
                        {
                          data: String,
                          media_type: Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestToolResultBlock::Content::UnionMember1::RequestImageBlock::Source::Base64ImageSource::media_type,
                          type: :base64
                        }

                      class Base64ImageSource < Sam::BaseModel
                        attr_accessor data: String

                        attr_accessor media_type: Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestToolResultBlock::Content::UnionMember1::RequestImageBlock::Source::Base64ImageSource::media_type

                        attr_accessor type: :base64

                        def initialize: (
                          data: String,
                          media_type: Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestToolResultBlock::Content::UnionMember1::RequestImageBlock::Source::Base64ImageSource::media_type,
                          ?type: :base64
                        ) -> void

                        def to_hash: -> Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestToolResultBlock::Content::UnionMember1::RequestImageBlock::Source::base64_image_source

                        type media_type =
                          :"image/jpeg"
                          | :"image/png"
                          | :"image/gif"
                          | :"image/webp"

                        module MediaType
                          extend Sam::Enum

                          IMAGE_JPEG: :"image/jpeg"
                          IMAGE_PNG: :"image/png"
                          IMAGE_GIF: :"image/gif"
                          IMAGE_WEBP: :"image/webp"

                          def self?.values: -> ::Array[Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestToolResultBlock::Content::UnionMember1::RequestImageBlock::Source::Base64ImageSource::media_type]
                        end
                      end

                      type url_image_source = { type: :url, url: String }

                      class URLImageSource < Sam::BaseModel
                        attr_accessor type: :url

                        attr_accessor url: String

                        def initialize: (url: String, ?type: :url) -> void

                        def to_hash: -> Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestToolResultBlock::Content::UnionMember1::RequestImageBlock::Source::url_image_source
                      end

                      def self?.variants: -> [Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestToolResultBlock::Content::UnionMember1::RequestImageBlock::Source::Base64ImageSource, Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestToolResultBlock::Content::UnionMember1::RequestImageBlock::Source::URLImageSource]
                    end

                    type cache_control = { type: :ephemeral }

                    class CacheControl < Sam::BaseModel
                      attr_accessor type: :ephemeral

                      def initialize: (?type: :ephemeral) -> void

                      def to_hash: -> Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestToolResultBlock::Content::UnionMember1::RequestImageBlock::cache_control
                    end
                  end

                  def self?.variants: -> [Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestToolResultBlock::Content::UnionMember1::RequestTextBlock, Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestToolResultBlock::Content::UnionMember1::RequestImageBlock]
                end

                def self?.variants: -> [String, ::Array[Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestToolResultBlock::Content::union_member1]]

                type union_member1_array =
                  ::Array[Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestToolResultBlock::Content::union_member1]

                UnionMember1Array: union_member1_array
              end
            end

            type request_document_block =
              {
                source: Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::source,
                type: :document,
                cache_control: Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::CacheControl?,
                citations: Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Citations,
                context: String?,
                title: String?
              }

            class RequestDocumentBlock < Sam::BaseModel
              attr_accessor source: Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::source

              attr_accessor type: :document

              attr_accessor cache_control: Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::CacheControl?

              attr_reader citations: Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Citations?

              def citations=: (
                Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Citations
              ) -> Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Citations

              attr_accessor context: String?

              attr_accessor title: String?

              def initialize: (
                source: Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::source,
                ?cache_control: Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::CacheControl?,
                ?citations: Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Citations,
                ?context: String?,
                ?title: String?,
                ?type: :document
              ) -> void

              def to_hash: -> Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::request_document_block

              type source =
                Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Source::Base64PdfSource
                | Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Source::PlainTextSource
                | Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Source::ContentBlockSource
                | Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Source::UrlpdfSource

              module Source
                extend Sam::Union

                type base64_pdf_source =
                  {
                    data: String,
                    media_type: :"application/pdf",
                    type: :base64
                  }

                class Base64PdfSource < Sam::BaseModel
                  attr_accessor data: String

                  attr_accessor media_type: :"application/pdf"

                  attr_accessor type: :base64

                  def initialize: (
                    data: String,
                    ?media_type: :"application/pdf",
                    ?type: :base64
                  ) -> void

                  def to_hash: -> Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Source::base64_pdf_source
                end

                type plain_text_source =
                  { data: String, media_type: :"text/plain", type: :text }

                class PlainTextSource < Sam::BaseModel
                  attr_accessor data: String

                  attr_accessor media_type: :"text/plain"

                  attr_accessor type: :text

                  def initialize: (
                    data: String,
                    ?media_type: :"text/plain",
                    ?type: :text
                  ) -> void

                  def to_hash: -> Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Source::plain_text_source
                end

                type content_block_source =
                  {
                    content: Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Source::ContentBlockSource::content,
                    type: :content
                  }

                class ContentBlockSource < Sam::BaseModel
                  attr_accessor content: Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Source::ContentBlockSource::content

                  attr_accessor type: :content

                  def initialize: (
                    content: Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Source::ContentBlockSource::content,
                    ?type: :content
                  ) -> void

                  def to_hash: -> Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Source::content_block_source

                  type content =
                    String
                    | ::Array[Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Source::ContentBlockSource::Content::union_member1]

                  module Content
                    extend Sam::Union

                    type union_member1 =
                      Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Source::ContentBlockSource::Content::UnionMember1::RequestTextBlock
                      | Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Source::ContentBlockSource::Content::UnionMember1::RequestImageBlock

                    module UnionMember1
                      extend Sam::Union

                      type request_text_block =
                        {
                          text: String,
                          type: :text,
                          cache_control: Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Source::ContentBlockSource::Content::UnionMember1::RequestTextBlock::CacheControl?,
                          citations: ::Array[Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Source::ContentBlockSource::Content::UnionMember1::RequestTextBlock::citation]?
                        }

                      class RequestTextBlock < Sam::BaseModel
                        attr_accessor text: String

                        attr_accessor type: :text

                        attr_accessor cache_control: Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Source::ContentBlockSource::Content::UnionMember1::RequestTextBlock::CacheControl?

                        attr_accessor citations: ::Array[Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Source::ContentBlockSource::Content::UnionMember1::RequestTextBlock::citation]?

                        def initialize: (
                          text: String,
                          ?cache_control: Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Source::ContentBlockSource::Content::UnionMember1::RequestTextBlock::CacheControl?,
                          ?citations: ::Array[Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Source::ContentBlockSource::Content::UnionMember1::RequestTextBlock::citation]?,
                          ?type: :text
                        ) -> void

                        def to_hash: -> Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Source::ContentBlockSource::Content::UnionMember1::request_text_block

                        type cache_control = { type: :ephemeral }

                        class CacheControl < Sam::BaseModel
                          attr_accessor type: :ephemeral

                          def initialize: (?type: :ephemeral) -> void

                          def to_hash: -> Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Source::ContentBlockSource::Content::UnionMember1::RequestTextBlock::cache_control
                        end

                        type citation =
                          Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Source::ContentBlockSource::Content::UnionMember1::RequestTextBlock::Citation::RequestCharLocationCitation
                          | Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Source::ContentBlockSource::Content::UnionMember1::RequestTextBlock::Citation::RequestPageLocationCitation
                          | Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Source::ContentBlockSource::Content::UnionMember1::RequestTextBlock::Citation::RequestContentBlockLocationCitation

                        module Citation
                          extend Sam::Union

                          type request_char_location_citation =
                            {
                              cited_text: String,
                              document_index: Integer,
                              document_title: String?,
                              end_char_index: Integer,
                              start_char_index: Integer,
                              type: :char_location
                            }

                          class RequestCharLocationCitation < Sam::BaseModel
                            attr_accessor cited_text: String

                            attr_accessor document_index: Integer

                            attr_accessor document_title: String?

                            attr_accessor end_char_index: Integer

                            attr_accessor start_char_index: Integer

                            attr_accessor type: :char_location

                            def initialize: (
                              cited_text: String,
                              document_index: Integer,
                              document_title: String?,
                              end_char_index: Integer,
                              start_char_index: Integer,
                              ?type: :char_location
                            ) -> void

                            def to_hash: -> Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Source::ContentBlockSource::Content::UnionMember1::RequestTextBlock::Citation::request_char_location_citation
                          end

                          type request_page_location_citation =
                            {
                              cited_text: String,
                              document_index: Integer,
                              document_title: String?,
                              end_page_number: Integer,
                              start_page_number: Integer,
                              type: :page_location
                            }

                          class RequestPageLocationCitation < Sam::BaseModel
                            attr_accessor cited_text: String

                            attr_accessor document_index: Integer

                            attr_accessor document_title: String?

                            attr_accessor end_page_number: Integer

                            attr_accessor start_page_number: Integer

                            attr_accessor type: :page_location

                            def initialize: (
                              cited_text: String,
                              document_index: Integer,
                              document_title: String?,
                              end_page_number: Integer,
                              start_page_number: Integer,
                              ?type: :page_location
                            ) -> void

                            def to_hash: -> Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Source::ContentBlockSource::Content::UnionMember1::RequestTextBlock::Citation::request_page_location_citation
                          end

                          type request_content_block_location_citation =
                            {
                              cited_text: String,
                              document_index: Integer,
                              document_title: String?,
                              end_block_index: Integer,
                              start_block_index: Integer,
                              type: :content_block_location
                            }

                          class RequestContentBlockLocationCitation < Sam::BaseModel
                            attr_accessor cited_text: String

                            attr_accessor document_index: Integer

                            attr_accessor document_title: String?

                            attr_accessor end_block_index: Integer

                            attr_accessor start_block_index: Integer

                            attr_accessor type: :content_block_location

                            def initialize: (
                              cited_text: String,
                              document_index: Integer,
                              document_title: String?,
                              end_block_index: Integer,
                              start_block_index: Integer,
                              ?type: :content_block_location
                            ) -> void

                            def to_hash: -> Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Source::ContentBlockSource::Content::UnionMember1::RequestTextBlock::Citation::request_content_block_location_citation
                          end

                          def self?.variants: -> [Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Source::ContentBlockSource::Content::UnionMember1::RequestTextBlock::Citation::RequestCharLocationCitation, Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Source::ContentBlockSource::Content::UnionMember1::RequestTextBlock::Citation::RequestPageLocationCitation, Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Source::ContentBlockSource::Content::UnionMember1::RequestTextBlock::Citation::RequestContentBlockLocationCitation]
                        end
                      end

                      type request_image_block =
                        {
                          source: Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Source::ContentBlockSource::Content::UnionMember1::RequestImageBlock::source,
                          type: :image,
                          cache_control: Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Source::ContentBlockSource::Content::UnionMember1::RequestImageBlock::CacheControl?
                        }

                      class RequestImageBlock < Sam::BaseModel
                        attr_accessor source: Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Source::ContentBlockSource::Content::UnionMember1::RequestImageBlock::source

                        attr_accessor type: :image

                        attr_accessor cache_control: Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Source::ContentBlockSource::Content::UnionMember1::RequestImageBlock::CacheControl?

                        def initialize: (
                          source: Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Source::ContentBlockSource::Content::UnionMember1::RequestImageBlock::source,
                          ?cache_control: Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Source::ContentBlockSource::Content::UnionMember1::RequestImageBlock::CacheControl?,
                          ?type: :image
                        ) -> void

                        def to_hash: -> Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Source::ContentBlockSource::Content::UnionMember1::request_image_block

                        type source =
                          Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Source::ContentBlockSource::Content::UnionMember1::RequestImageBlock::Source::Base64ImageSource
                          | Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Source::ContentBlockSource::Content::UnionMember1::RequestImageBlock::Source::URLImageSource

                        module Source
                          extend Sam::Union

                          type base64_image_source =
                            {
                              data: String,
                              media_type: Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Source::ContentBlockSource::Content::UnionMember1::RequestImageBlock::Source::Base64ImageSource::media_type,
                              type: :base64
                            }

                          class Base64ImageSource < Sam::BaseModel
                            attr_accessor data: String

                            attr_accessor media_type: Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Source::ContentBlockSource::Content::UnionMember1::RequestImageBlock::Source::Base64ImageSource::media_type

                            attr_accessor type: :base64

                            def initialize: (
                              data: String,
                              media_type: Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Source::ContentBlockSource::Content::UnionMember1::RequestImageBlock::Source::Base64ImageSource::media_type,
                              ?type: :base64
                            ) -> void

                            def to_hash: -> Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Source::ContentBlockSource::Content::UnionMember1::RequestImageBlock::Source::base64_image_source

                            type media_type =
                              :"image/jpeg"
                              | :"image/png"
                              | :"image/gif"
                              | :"image/webp"

                            module MediaType
                              extend Sam::Enum

                              IMAGE_JPEG: :"image/jpeg"
                              IMAGE_PNG: :"image/png"
                              IMAGE_GIF: :"image/gif"
                              IMAGE_WEBP: :"image/webp"

                              def self?.values: -> ::Array[Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Source::ContentBlockSource::Content::UnionMember1::RequestImageBlock::Source::Base64ImageSource::media_type]
                            end
                          end

                          type url_image_source = { type: :url, url: String }

                          class URLImageSource < Sam::BaseModel
                            attr_accessor type: :url

                            attr_accessor url: String

                            def initialize: (url: String, ?type: :url) -> void

                            def to_hash: -> Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Source::ContentBlockSource::Content::UnionMember1::RequestImageBlock::Source::url_image_source
                          end

                          def self?.variants: -> [Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Source::ContentBlockSource::Content::UnionMember1::RequestImageBlock::Source::Base64ImageSource, Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Source::ContentBlockSource::Content::UnionMember1::RequestImageBlock::Source::URLImageSource]
                        end

                        type cache_control = { type: :ephemeral }

                        class CacheControl < Sam::BaseModel
                          attr_accessor type: :ephemeral

                          def initialize: (?type: :ephemeral) -> void

                          def to_hash: -> Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Source::ContentBlockSource::Content::UnionMember1::RequestImageBlock::cache_control
                        end
                      end

                      def self?.variants: -> [Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Source::ContentBlockSource::Content::UnionMember1::RequestTextBlock, Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Source::ContentBlockSource::Content::UnionMember1::RequestImageBlock]
                    end

                    def self?.variants: -> [String, ::Array[Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Source::ContentBlockSource::Content::union_member1]]

                    type union_member1_array =
                      ::Array[Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Source::ContentBlockSource::Content::union_member1]

                    UnionMember1Array: union_member1_array
                  end
                end

                type urlpdf_source = { type: :url, url: String }

                class UrlpdfSource < Sam::BaseModel
                  attr_accessor type: :url

                  attr_accessor url: String

                  def initialize: (url: String, ?type: :url) -> void

                  def to_hash: -> Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Source::urlpdf_source
                end

                def self?.variants: -> [Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Source::Base64PdfSource, Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Source::PlainTextSource, Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Source::ContentBlockSource, Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::Source::UrlpdfSource]
              end

              type cache_control = { type: :ephemeral }

              class CacheControl < Sam::BaseModel
                attr_accessor type: :ephemeral

                def initialize: (?type: :ephemeral) -> void

                def to_hash: -> Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::cache_control
              end

              type citations = { enabled: bool }

              class Citations < Sam::BaseModel
                attr_reader enabled: bool?

                def enabled=: (bool) -> bool

                def initialize: (?enabled: bool) -> void

                def to_hash: -> Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock::citations
              end
            end

            type request_thinking_block =
              { signature: String, thinking: String, type: :thinking }

            class RequestThinkingBlock < Sam::BaseModel
              attr_accessor signature: String

              attr_accessor thinking: String

              attr_accessor type: :thinking

              def initialize: (
                signature: String,
                thinking: String,
                ?type: :thinking
              ) -> void

              def to_hash: -> Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::request_thinking_block
            end

            type request_redacted_thinking_block =
              { data: String, type: :redacted_thinking }

            class RequestRedactedThinkingBlock < Sam::BaseModel
              attr_accessor data: String

              attr_accessor type: :redacted_thinking

              def initialize: (data: String, ?type: :redacted_thinking) -> void

              def to_hash: -> Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::request_redacted_thinking_block
            end

            def self?.variants: -> [Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestTextBlock, Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestImageBlock, Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestToolUseBlock, Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestToolResultBlock, Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestDocumentBlock, Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestThinkingBlock, Sam::Models::MessageCountTokensParams::Message::Content::UnionMember1::RequestRedactedThinkingBlock]
          end

          def self?.variants: -> [String, ::Array[Sam::Models::MessageCountTokensParams::Message::Content::union_member1]]

          type union_member1_array =
            ::Array[Sam::Models::MessageCountTokensParams::Message::Content::union_member1]

          UnionMember1Array: union_member1_array
        end

        type role = :user | :assistant

        module Role
          extend Sam::Enum

          USER: :user
          ASSISTANT: :assistant

          def self?.values: -> ::Array[Sam::Models::MessageCountTokensParams::Message::role]
        end
      end

      type system_ =
        String
        | ::Array[Sam::Models::MessageCountTokensParams::System::UnionMember1]

      module System
        extend Sam::Union

        type union_member1 =
          {
            text: String,
            type: :text,
            cache_control: Sam::Models::MessageCountTokensParams::System::UnionMember1::CacheControl?,
            citations: ::Array[Sam::Models::MessageCountTokensParams::System::UnionMember1::citation]?
          }

        class UnionMember1 < Sam::BaseModel
          attr_accessor text: String

          attr_accessor type: :text

          attr_accessor cache_control: Sam::Models::MessageCountTokensParams::System::UnionMember1::CacheControl?

          attr_accessor citations: ::Array[Sam::Models::MessageCountTokensParams::System::UnionMember1::citation]?

          def initialize: (
            text: String,
            ?cache_control: Sam::Models::MessageCountTokensParams::System::UnionMember1::CacheControl?,
            ?citations: ::Array[Sam::Models::MessageCountTokensParams::System::UnionMember1::citation]?,
            ?type: :text
          ) -> void

          def to_hash: -> Sam::Models::MessageCountTokensParams::System::union_member1

          type cache_control = { type: :ephemeral }

          class CacheControl < Sam::BaseModel
            attr_accessor type: :ephemeral

            def initialize: (?type: :ephemeral) -> void

            def to_hash: -> Sam::Models::MessageCountTokensParams::System::UnionMember1::cache_control
          end

          type citation =
            Sam::Models::MessageCountTokensParams::System::UnionMember1::Citation::RequestCharLocationCitation
            | Sam::Models::MessageCountTokensParams::System::UnionMember1::Citation::RequestPageLocationCitation
            | Sam::Models::MessageCountTokensParams::System::UnionMember1::Citation::RequestContentBlockLocationCitation

          module Citation
            extend Sam::Union

            type request_char_location_citation =
              {
                cited_text: String,
                document_index: Integer,
                document_title: String?,
                end_char_index: Integer,
                start_char_index: Integer,
                type: :char_location
              }

            class RequestCharLocationCitation < Sam::BaseModel
              attr_accessor cited_text: String

              attr_accessor document_index: Integer

              attr_accessor document_title: String?

              attr_accessor end_char_index: Integer

              attr_accessor start_char_index: Integer

              attr_accessor type: :char_location

              def initialize: (
                cited_text: String,
                document_index: Integer,
                document_title: String?,
                end_char_index: Integer,
                start_char_index: Integer,
                ?type: :char_location
              ) -> void

              def to_hash: -> Sam::Models::MessageCountTokensParams::System::UnionMember1::Citation::request_char_location_citation
            end

            type request_page_location_citation =
              {
                cited_text: String,
                document_index: Integer,
                document_title: String?,
                end_page_number: Integer,
                start_page_number: Integer,
                type: :page_location
              }

            class RequestPageLocationCitation < Sam::BaseModel
              attr_accessor cited_text: String

              attr_accessor document_index: Integer

              attr_accessor document_title: String?

              attr_accessor end_page_number: Integer

              attr_accessor start_page_number: Integer

              attr_accessor type: :page_location

              def initialize: (
                cited_text: String,
                document_index: Integer,
                document_title: String?,
                end_page_number: Integer,
                start_page_number: Integer,
                ?type: :page_location
              ) -> void

              def to_hash: -> Sam::Models::MessageCountTokensParams::System::UnionMember1::Citation::request_page_location_citation
            end

            type request_content_block_location_citation =
              {
                cited_text: String,
                document_index: Integer,
                document_title: String?,
                end_block_index: Integer,
                start_block_index: Integer,
                type: :content_block_location
              }

            class RequestContentBlockLocationCitation < Sam::BaseModel
              attr_accessor cited_text: String

              attr_accessor document_index: Integer

              attr_accessor document_title: String?

              attr_accessor end_block_index: Integer

              attr_accessor start_block_index: Integer

              attr_accessor type: :content_block_location

              def initialize: (
                cited_text: String,
                document_index: Integer,
                document_title: String?,
                end_block_index: Integer,
                start_block_index: Integer,
                ?type: :content_block_location
              ) -> void

              def to_hash: -> Sam::Models::MessageCountTokensParams::System::UnionMember1::Citation::request_content_block_location_citation
            end

            def self?.variants: -> [Sam::Models::MessageCountTokensParams::System::UnionMember1::Citation::RequestCharLocationCitation, Sam::Models::MessageCountTokensParams::System::UnionMember1::Citation::RequestPageLocationCitation, Sam::Models::MessageCountTokensParams::System::UnionMember1::Citation::RequestContentBlockLocationCitation]
          end
        end

        def self?.variants: -> [String, ::Array[Sam::Models::MessageCountTokensParams::System::UnionMember1]]

        type union_member1_array =
          ::Array[Sam::Models::MessageCountTokensParams::System::UnionMember1]

        UnionMember1Array: union_member1_array
      end

      type thinking =
        Sam::Models::MessageCountTokensParams::Thinking::ThinkingConfigEnabled
        | Sam::Models::MessageCountTokensParams::Thinking::ThinkingConfigDisabled

      module Thinking
        extend Sam::Union

        type thinking_config_enabled =
          { budget_tokens: Integer, type: :enabled }

        class ThinkingConfigEnabled < Sam::BaseModel
          attr_accessor budget_tokens: Integer

          attr_accessor type: :enabled

          def initialize: (budget_tokens: Integer, ?type: :enabled) -> void

          def to_hash: -> Sam::Models::MessageCountTokensParams::Thinking::thinking_config_enabled
        end

        type thinking_config_disabled = { type: :disabled }

        class ThinkingConfigDisabled < Sam::BaseModel
          attr_accessor type: :disabled

          def initialize: (?type: :disabled) -> void

          def to_hash: -> Sam::Models::MessageCountTokensParams::Thinking::thinking_config_disabled
        end

        def self?.variants: -> [Sam::Models::MessageCountTokensParams::Thinking::ThinkingConfigEnabled, Sam::Models::MessageCountTokensParams::Thinking::ThinkingConfigDisabled]
      end

      type tool_choice =
        Sam::Models::MessageCountTokensParams::ToolChoice::ToolChoiceAuto
        | Sam::Models::MessageCountTokensParams::ToolChoice::ToolChoiceAny
        | Sam::Models::MessageCountTokensParams::ToolChoice::ToolChoiceTool
        | Sam::Models::MessageCountTokensParams::ToolChoice::ToolChoiceNone

      module ToolChoice
        extend Sam::Union

        type tool_choice_auto = { type: :auto, disable_parallel_tool_use: bool }

        class ToolChoiceAuto < Sam::BaseModel
          attr_accessor type: :auto

          attr_reader disable_parallel_tool_use: bool?

          def disable_parallel_tool_use=: (bool) -> bool

          def initialize: (
            ?disable_parallel_tool_use: bool,
            ?type: :auto
          ) -> void

          def to_hash: -> Sam::Models::MessageCountTokensParams::ToolChoice::tool_choice_auto
        end

        type tool_choice_any = { type: :any, disable_parallel_tool_use: bool }

        class ToolChoiceAny < Sam::BaseModel
          attr_accessor type: :any

          attr_reader disable_parallel_tool_use: bool?

          def disable_parallel_tool_use=: (bool) -> bool

          def initialize: (
            ?disable_parallel_tool_use: bool,
            ?type: :any
          ) -> void

          def to_hash: -> Sam::Models::MessageCountTokensParams::ToolChoice::tool_choice_any
        end

        type tool_choice_tool =
          { name: String, type: :tool, disable_parallel_tool_use: bool }

        class ToolChoiceTool < Sam::BaseModel
          attr_accessor name: String

          attr_accessor type: :tool

          attr_reader disable_parallel_tool_use: bool?

          def disable_parallel_tool_use=: (bool) -> bool

          def initialize: (
            name: String,
            ?disable_parallel_tool_use: bool,
            ?type: :tool
          ) -> void

          def to_hash: -> Sam::Models::MessageCountTokensParams::ToolChoice::tool_choice_tool
        end

        type tool_choice_none = { type: :none }

        class ToolChoiceNone < Sam::BaseModel
          attr_accessor type: :none

          def initialize: (?type: :none) -> void

          def to_hash: -> Sam::Models::MessageCountTokensParams::ToolChoice::tool_choice_none
        end

        def self?.variants: -> [Sam::Models::MessageCountTokensParams::ToolChoice::ToolChoiceAuto, Sam::Models::MessageCountTokensParams::ToolChoice::ToolChoiceAny, Sam::Models::MessageCountTokensParams::ToolChoice::ToolChoiceTool, Sam::Models::MessageCountTokensParams::ToolChoice::ToolChoiceNone]
      end

      type tool =
        Sam::Models::MessageCountTokensParams::Tool::Tool
        | Sam::Models::MessageCountTokensParams::Tool::BashTool20250124
        | Sam::Models::MessageCountTokensParams::Tool::TextEditor20250124

      module Tool
        extend Sam::Union

        type tool =
          {
            input_schema: Sam::Models::MessageCountTokensParams::Tool::Tool::InputSchema,
            name: String,
            cache_control: Sam::Models::MessageCountTokensParams::Tool::Tool::CacheControl?,
            description: String
          }

        class Tool < Sam::BaseModel
          attr_accessor input_schema: Sam::Models::MessageCountTokensParams::Tool::Tool::InputSchema

          attr_accessor name: String

          attr_accessor cache_control: Sam::Models::MessageCountTokensParams::Tool::Tool::CacheControl?

          attr_reader description: String?

          def description=: (String) -> String

          def initialize: (
            input_schema: Sam::Models::MessageCountTokensParams::Tool::Tool::InputSchema,
            name: String,
            ?cache_control: Sam::Models::MessageCountTokensParams::Tool::Tool::CacheControl?,
            ?description: String
          ) -> void

          def to_hash: -> Sam::Models::MessageCountTokensParams::Tool::tool

          type input_schema = { type: :object, properties: top? }

          class InputSchema < Sam::BaseModel
            attr_accessor type: :object

            attr_accessor properties: top?

            def initialize: (?properties: top?, ?type: :object) -> void

            def to_hash: -> Sam::Models::MessageCountTokensParams::Tool::Tool::input_schema
          end

          type cache_control = { type: :ephemeral }

          class CacheControl < Sam::BaseModel
            attr_accessor type: :ephemeral

            def initialize: (?type: :ephemeral) -> void

            def to_hash: -> Sam::Models::MessageCountTokensParams::Tool::Tool::cache_control
          end
        end

        type bash_tool20250124 =
          {
            name: :bash,
            type: :bash_20250124,
            cache_control: Sam::Models::MessageCountTokensParams::Tool::BashTool20250124::CacheControl?
          }

        class BashTool20250124 < Sam::BaseModel
          attr_accessor name: :bash

          attr_accessor type: :bash_20250124

          attr_accessor cache_control: Sam::Models::MessageCountTokensParams::Tool::BashTool20250124::CacheControl?

          def initialize: (
            ?cache_control: Sam::Models::MessageCountTokensParams::Tool::BashTool20250124::CacheControl?,
            ?name: :bash,
            ?type: :bash_20250124
          ) -> void

          def to_hash: -> Sam::Models::MessageCountTokensParams::Tool::bash_tool20250124

          type cache_control = { type: :ephemeral }

          class CacheControl < Sam::BaseModel
            attr_accessor type: :ephemeral

            def initialize: (?type: :ephemeral) -> void

            def to_hash: -> Sam::Models::MessageCountTokensParams::Tool::BashTool20250124::cache_control
          end
        end

        type text_editor20250124 =
          {
            name: :str_replace_editor,
            type: :text_editor_20250124,
            cache_control: Sam::Models::MessageCountTokensParams::Tool::TextEditor20250124::CacheControl?
          }

        class TextEditor20250124 < Sam::BaseModel
          attr_accessor name: :str_replace_editor

          attr_accessor type: :text_editor_20250124

          attr_accessor cache_control: Sam::Models::MessageCountTokensParams::Tool::TextEditor20250124::CacheControl?

          def initialize: (
            ?cache_control: Sam::Models::MessageCountTokensParams::Tool::TextEditor20250124::CacheControl?,
            ?name: :str_replace_editor,
            ?type: :text_editor_20250124
          ) -> void

          def to_hash: -> Sam::Models::MessageCountTokensParams::Tool::text_editor20250124

          type cache_control = { type: :ephemeral }

          class CacheControl < Sam::BaseModel
            attr_accessor type: :ephemeral

            def initialize: (?type: :ephemeral) -> void

            def to_hash: -> Sam::Models::MessageCountTokensParams::Tool::TextEditor20250124::cache_control
          end
        end

        def self?.variants: -> [Sam::Models::MessageCountTokensParams::Tool::Tool, Sam::Models::MessageCountTokensParams::Tool::BashTool20250124, Sam::Models::MessageCountTokensParams::Tool::TextEditor20250124]
      end
    end
  end
end
