module Sam
  module Models
    type message_count_tokens_beta_params =
      {
        messages: ::Array[Sam::Models::MessageCountTokensBetaParams::Message],
        model: String,
        system_: Sam::Models::MessageCountTokensBetaParams::system_,
        thinking: Sam::Models::MessageCountTokensBetaParams::thinking,
        tool_choice: Sam::Models::MessageCountTokensBetaParams::tool_choice,
        tools: ::Array[Sam::Models::MessageCountTokensBetaParams::tool],
        anthropic_beta: ::Array[String],
        anthropic_version: String,
        x_api_key: String
      }
      & Sam::Internal::Type::request_parameters

    class MessageCountTokensBetaParams < Sam::Internal::Type::BaseModel
      extend Sam::Internal::Type::RequestParameters::Converter
      include Sam::Internal::Type::RequestParameters

      attr_accessor messages: ::Array[Sam::Models::MessageCountTokensBetaParams::Message]

      attr_accessor model: String

      attr_reader system_: Sam::Models::MessageCountTokensBetaParams::system_?

      def system_=: (
        Sam::Models::MessageCountTokensBetaParams::system_
      ) -> Sam::Models::MessageCountTokensBetaParams::system_

      attr_reader thinking: Sam::Models::MessageCountTokensBetaParams::thinking?

      def thinking=: (
        Sam::Models::MessageCountTokensBetaParams::thinking
      ) -> Sam::Models::MessageCountTokensBetaParams::thinking

      attr_reader tool_choice: Sam::Models::MessageCountTokensBetaParams::tool_choice?

      def tool_choice=: (
        Sam::Models::MessageCountTokensBetaParams::tool_choice
      ) -> Sam::Models::MessageCountTokensBetaParams::tool_choice

      attr_reader tools: ::Array[Sam::Models::MessageCountTokensBetaParams::tool]?

      def tools=: (
        ::Array[Sam::Models::MessageCountTokensBetaParams::tool]
      ) -> ::Array[Sam::Models::MessageCountTokensBetaParams::tool]

      attr_reader anthropic_beta: ::Array[String]?

      def anthropic_beta=: (::Array[String]) -> ::Array[String]

      attr_reader anthropic_version: String?

      def anthropic_version=: (String) -> String

      attr_reader x_api_key: String?

      def x_api_key=: (String) -> String

      def initialize: (
        messages: ::Array[Sam::Models::MessageCountTokensBetaParams::Message],
        model: String,
        ?system_: Sam::Models::MessageCountTokensBetaParams::system_,
        ?thinking: Sam::Models::MessageCountTokensBetaParams::thinking,
        ?tool_choice: Sam::Models::MessageCountTokensBetaParams::tool_choice,
        ?tools: ::Array[Sam::Models::MessageCountTokensBetaParams::tool],
        ?anthropic_beta: ::Array[String],
        ?anthropic_version: String,
        ?x_api_key: String,
        ?request_options: Sam::request_opts
      ) -> void

      def to_hash: -> Sam::Models::message_count_tokens_beta_params

      type message =
        {
          content: Sam::Models::MessageCountTokensBetaParams::Message::content,
          role: Sam::Models::MessageCountTokensBetaParams::Message::role
        }

      class Message < Sam::Internal::Type::BaseModel
        attr_accessor content: Sam::Models::MessageCountTokensBetaParams::Message::content

        attr_accessor role: Sam::Models::MessageCountTokensBetaParams::Message::role

        def initialize: (
          content: Sam::Models::MessageCountTokensBetaParams::Message::content,
          role: Sam::Models::MessageCountTokensBetaParams::Message::role
        ) -> void

        def to_hash: -> Sam::Models::MessageCountTokensBetaParams::message

        type content =
          String
          | ::Array[Sam::Models::MessageCountTokensBetaParams::Message::Content::union_member1]

        module Content
          extend Sam::Internal::Type::Union

          type union_member1 =
            Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Text
            | Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Image
            | Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::ToolUse
            | Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::ToolResult
            | Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document
            | Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Thinking
            | Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::RedactedThinking

          module UnionMember1
            extend Sam::Internal::Type::Union

            type text =
              {
                text: String,
                type: :text,
                cache_control: Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Text::CacheControl?,
                citations: ::Array[Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Text::citation]?
              }

            class Text < Sam::Internal::Type::BaseModel
              attr_accessor text: String

              attr_accessor type: :text

              attr_accessor cache_control: Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Text::CacheControl?

              attr_accessor citations: ::Array[Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Text::citation]?

              def initialize: (
                text: String,
                ?cache_control: Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Text::CacheControl?,
                ?citations: ::Array[Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Text::citation]?,
                ?type: :text
              ) -> void

              def to_hash: -> Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::text

              type cache_control = { type: :ephemeral }

              class CacheControl < Sam::Internal::Type::BaseModel
                attr_accessor type: :ephemeral

                def initialize: (?type: :ephemeral) -> void

                def to_hash: -> Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Text::cache_control
              end

              type citation =
                Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Text::Citation::CharLocation
                | Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Text::Citation::PageLocation
                | Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Text::Citation::ContentBlockLocation

              module Citation
                extend Sam::Internal::Type::Union

                type char_location =
                  {
                    cited_text: String,
                    document_index: Integer,
                    document_title: String?,
                    end_char_index: Integer,
                    start_char_index: Integer,
                    type: :char_location
                  }

                class CharLocation < Sam::Internal::Type::BaseModel
                  attr_accessor cited_text: String

                  attr_accessor document_index: Integer

                  attr_accessor document_title: String?

                  attr_accessor end_char_index: Integer

                  attr_accessor start_char_index: Integer

                  attr_accessor type: :char_location

                  def initialize: (
                    cited_text: String,
                    document_index: Integer,
                    document_title: String?,
                    end_char_index: Integer,
                    start_char_index: Integer,
                    ?type: :char_location
                  ) -> void

                  def to_hash: -> Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Text::Citation::char_location
                end

                type page_location =
                  {
                    cited_text: String,
                    document_index: Integer,
                    document_title: String?,
                    end_page_number: Integer,
                    start_page_number: Integer,
                    type: :page_location
                  }

                class PageLocation < Sam::Internal::Type::BaseModel
                  attr_accessor cited_text: String

                  attr_accessor document_index: Integer

                  attr_accessor document_title: String?

                  attr_accessor end_page_number: Integer

                  attr_accessor start_page_number: Integer

                  attr_accessor type: :page_location

                  def initialize: (
                    cited_text: String,
                    document_index: Integer,
                    document_title: String?,
                    end_page_number: Integer,
                    start_page_number: Integer,
                    ?type: :page_location
                  ) -> void

                  def to_hash: -> Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Text::Citation::page_location
                end

                type content_block_location =
                  {
                    cited_text: String,
                    document_index: Integer,
                    document_title: String?,
                    end_block_index: Integer,
                    start_block_index: Integer,
                    type: :content_block_location
                  }

                class ContentBlockLocation < Sam::Internal::Type::BaseModel
                  attr_accessor cited_text: String

                  attr_accessor document_index: Integer

                  attr_accessor document_title: String?

                  attr_accessor end_block_index: Integer

                  attr_accessor start_block_index: Integer

                  attr_accessor type: :content_block_location

                  def initialize: (
                    cited_text: String,
                    document_index: Integer,
                    document_title: String?,
                    end_block_index: Integer,
                    start_block_index: Integer,
                    ?type: :content_block_location
                  ) -> void

                  def to_hash: -> Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Text::Citation::content_block_location
                end

                def self?.variants: -> [Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Text::Citation::CharLocation, Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Text::Citation::PageLocation, Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Text::Citation::ContentBlockLocation]
              end
            end

            type image =
              {
                source: Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Image::source,
                type: :image,
                cache_control: Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Image::CacheControl?
              }

            class Image < Sam::Internal::Type::BaseModel
              attr_accessor source: Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Image::source

              attr_accessor type: :image

              attr_accessor cache_control: Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Image::CacheControl?

              def initialize: (
                source: Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Image::source,
                ?cache_control: Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Image::CacheControl?,
                ?type: :image
              ) -> void

              def to_hash: -> Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::image

              type source =
                Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Image::Source::Base64
                | Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Image::Source::URL

              module Source
                extend Sam::Internal::Type::Union

                type base64 =
                  {
                    data: String,
                    media_type: Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Image::Source::Base64::media_type,
                    type: :base64
                  }

                class Base64 < Sam::Internal::Type::BaseModel
                  attr_accessor data: String

                  attr_accessor media_type: Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Image::Source::Base64::media_type

                  attr_accessor type: :base64

                  def initialize: (
                    data: String,
                    media_type: Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Image::Source::Base64::media_type,
                    ?type: :base64
                  ) -> void

                  def to_hash: -> Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Image::Source::base64

                  type media_type =
                    :"image/jpeg" | :"image/png" | :"image/gif" | :"image/webp"

                  module MediaType
                    extend Sam::Internal::Type::Enum

                    IMAGE_JPEG: :"image/jpeg"
                    IMAGE_PNG: :"image/png"
                    IMAGE_GIF: :"image/gif"
                    IMAGE_WEBP: :"image/webp"

                    def self?.values: -> ::Array[Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Image::Source::Base64::media_type]
                  end
                end

                type url = { type: :url, url: String }

                class URL < Sam::Internal::Type::BaseModel
                  attr_accessor type: :url

                  attr_accessor url: String

                  def initialize: (url: String, ?type: :url) -> void

                  def to_hash: -> Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Image::Source::url
                end

                def self?.variants: -> [Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Image::Source::Base64, Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Image::Source::URL]
              end

              type cache_control = { type: :ephemeral }

              class CacheControl < Sam::Internal::Type::BaseModel
                attr_accessor type: :ephemeral

                def initialize: (?type: :ephemeral) -> void

                def to_hash: -> Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Image::cache_control
              end
            end

            type tool_use =
              {
                id: String,
                input: top,
                name: String,
                type: :tool_use,
                cache_control: Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::ToolUse::CacheControl?
              }

            class ToolUse < Sam::Internal::Type::BaseModel
              attr_accessor id: String

              attr_accessor input: top

              attr_accessor name: String

              attr_accessor type: :tool_use

              attr_accessor cache_control: Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::ToolUse::CacheControl?

              def initialize: (
                id: String,
                input: top,
                name: String,
                ?cache_control: Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::ToolUse::CacheControl?,
                ?type: :tool_use
              ) -> void

              def to_hash: -> Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::tool_use

              type cache_control = { type: :ephemeral }

              class CacheControl < Sam::Internal::Type::BaseModel
                attr_accessor type: :ephemeral

                def initialize: (?type: :ephemeral) -> void

                def to_hash: -> Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::ToolUse::cache_control
              end
            end

            type tool_result =
              {
                tool_use_id: String,
                type: :tool_result,
                cache_control: Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::ToolResult::CacheControl?,
                content: Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::ToolResult::content,
                is_error: bool
              }

            class ToolResult < Sam::Internal::Type::BaseModel
              attr_accessor tool_use_id: String

              attr_accessor type: :tool_result

              attr_accessor cache_control: Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::ToolResult::CacheControl?

              attr_reader content: Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::ToolResult::content?

              def content=: (
                Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::ToolResult::content
              ) -> Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::ToolResult::content

              attr_reader is_error: bool?

              def is_error=: (bool) -> bool

              def initialize: (
                tool_use_id: String,
                ?cache_control: Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::ToolResult::CacheControl?,
                ?content: Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::ToolResult::content,
                ?is_error: bool,
                ?type: :tool_result
              ) -> void

              def to_hash: -> Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::tool_result

              type cache_control = { type: :ephemeral }

              class CacheControl < Sam::Internal::Type::BaseModel
                attr_accessor type: :ephemeral

                def initialize: (?type: :ephemeral) -> void

                def to_hash: -> Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::ToolResult::cache_control
              end

              type content =
                String
                | ::Array[Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::ToolResult::Content::union_member1]

              module Content
                extend Sam::Internal::Type::Union

                type union_member1 =
                  Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::ToolResult::Content::UnionMember1::Text
                  | Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::ToolResult::Content::UnionMember1::Image

                module UnionMember1
                  extend Sam::Internal::Type::Union

                  type text =
                    {
                      text: String,
                      type: :text,
                      cache_control: Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::ToolResult::Content::UnionMember1::Text::CacheControl?,
                      citations: ::Array[Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::ToolResult::Content::UnionMember1::Text::citation]?
                    }

                  class Text < Sam::Internal::Type::BaseModel
                    attr_accessor text: String

                    attr_accessor type: :text

                    attr_accessor cache_control: Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::ToolResult::Content::UnionMember1::Text::CacheControl?

                    attr_accessor citations: ::Array[Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::ToolResult::Content::UnionMember1::Text::citation]?

                    def initialize: (
                      text: String,
                      ?cache_control: Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::ToolResult::Content::UnionMember1::Text::CacheControl?,
                      ?citations: ::Array[Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::ToolResult::Content::UnionMember1::Text::citation]?,
                      ?type: :text
                    ) -> void

                    def to_hash: -> Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::ToolResult::Content::UnionMember1::text

                    type cache_control = { type: :ephemeral }

                    class CacheControl < Sam::Internal::Type::BaseModel
                      attr_accessor type: :ephemeral

                      def initialize: (?type: :ephemeral) -> void

                      def to_hash: -> Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::ToolResult::Content::UnionMember1::Text::cache_control
                    end

                    type citation =
                      Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::ToolResult::Content::UnionMember1::Text::Citation::CharLocation
                      | Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::ToolResult::Content::UnionMember1::Text::Citation::PageLocation
                      | Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::ToolResult::Content::UnionMember1::Text::Citation::ContentBlockLocation

                    module Citation
                      extend Sam::Internal::Type::Union

                      type char_location =
                        {
                          cited_text: String,
                          document_index: Integer,
                          document_title: String?,
                          end_char_index: Integer,
                          start_char_index: Integer,
                          type: :char_location
                        }

                      class CharLocation < Sam::Internal::Type::BaseModel
                        attr_accessor cited_text: String

                        attr_accessor document_index: Integer

                        attr_accessor document_title: String?

                        attr_accessor end_char_index: Integer

                        attr_accessor start_char_index: Integer

                        attr_accessor type: :char_location

                        def initialize: (
                          cited_text: String,
                          document_index: Integer,
                          document_title: String?,
                          end_char_index: Integer,
                          start_char_index: Integer,
                          ?type: :char_location
                        ) -> void

                        def to_hash: -> Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::ToolResult::Content::UnionMember1::Text::Citation::char_location
                      end

                      type page_location =
                        {
                          cited_text: String,
                          document_index: Integer,
                          document_title: String?,
                          end_page_number: Integer,
                          start_page_number: Integer,
                          type: :page_location
                        }

                      class PageLocation < Sam::Internal::Type::BaseModel
                        attr_accessor cited_text: String

                        attr_accessor document_index: Integer

                        attr_accessor document_title: String?

                        attr_accessor end_page_number: Integer

                        attr_accessor start_page_number: Integer

                        attr_accessor type: :page_location

                        def initialize: (
                          cited_text: String,
                          document_index: Integer,
                          document_title: String?,
                          end_page_number: Integer,
                          start_page_number: Integer,
                          ?type: :page_location
                        ) -> void

                        def to_hash: -> Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::ToolResult::Content::UnionMember1::Text::Citation::page_location
                      end

                      type content_block_location =
                        {
                          cited_text: String,
                          document_index: Integer,
                          document_title: String?,
                          end_block_index: Integer,
                          start_block_index: Integer,
                          type: :content_block_location
                        }

                      class ContentBlockLocation < Sam::Internal::Type::BaseModel
                        attr_accessor cited_text: String

                        attr_accessor document_index: Integer

                        attr_accessor document_title: String?

                        attr_accessor end_block_index: Integer

                        attr_accessor start_block_index: Integer

                        attr_accessor type: :content_block_location

                        def initialize: (
                          cited_text: String,
                          document_index: Integer,
                          document_title: String?,
                          end_block_index: Integer,
                          start_block_index: Integer,
                          ?type: :content_block_location
                        ) -> void

                        def to_hash: -> Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::ToolResult::Content::UnionMember1::Text::Citation::content_block_location
                      end

                      def self?.variants: -> [Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::ToolResult::Content::UnionMember1::Text::Citation::CharLocation, Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::ToolResult::Content::UnionMember1::Text::Citation::PageLocation, Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::ToolResult::Content::UnionMember1::Text::Citation::ContentBlockLocation]
                    end
                  end

                  type image =
                    {
                      source: Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::ToolResult::Content::UnionMember1::Image::source,
                      type: :image,
                      cache_control: Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::ToolResult::Content::UnionMember1::Image::CacheControl?
                    }

                  class Image < Sam::Internal::Type::BaseModel
                    attr_accessor source: Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::ToolResult::Content::UnionMember1::Image::source

                    attr_accessor type: :image

                    attr_accessor cache_control: Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::ToolResult::Content::UnionMember1::Image::CacheControl?

                    def initialize: (
                      source: Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::ToolResult::Content::UnionMember1::Image::source,
                      ?cache_control: Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::ToolResult::Content::UnionMember1::Image::CacheControl?,
                      ?type: :image
                    ) -> void

                    def to_hash: -> Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::ToolResult::Content::UnionMember1::image

                    type source =
                      Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::ToolResult::Content::UnionMember1::Image::Source::Base64
                      | Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::ToolResult::Content::UnionMember1::Image::Source::URL

                    module Source
                      extend Sam::Internal::Type::Union

                      type base64 =
                        {
                          data: String,
                          media_type: Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::ToolResult::Content::UnionMember1::Image::Source::Base64::media_type,
                          type: :base64
                        }

                      class Base64 < Sam::Internal::Type::BaseModel
                        attr_accessor data: String

                        attr_accessor media_type: Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::ToolResult::Content::UnionMember1::Image::Source::Base64::media_type

                        attr_accessor type: :base64

                        def initialize: (
                          data: String,
                          media_type: Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::ToolResult::Content::UnionMember1::Image::Source::Base64::media_type,
                          ?type: :base64
                        ) -> void

                        def to_hash: -> Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::ToolResult::Content::UnionMember1::Image::Source::base64

                        type media_type =
                          :"image/jpeg"
                          | :"image/png"
                          | :"image/gif"
                          | :"image/webp"

                        module MediaType
                          extend Sam::Internal::Type::Enum

                          IMAGE_JPEG: :"image/jpeg"
                          IMAGE_PNG: :"image/png"
                          IMAGE_GIF: :"image/gif"
                          IMAGE_WEBP: :"image/webp"

                          def self?.values: -> ::Array[Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::ToolResult::Content::UnionMember1::Image::Source::Base64::media_type]
                        end
                      end

                      type url = { type: :url, url: String }

                      class URL < Sam::Internal::Type::BaseModel
                        attr_accessor type: :url

                        attr_accessor url: String

                        def initialize: (url: String, ?type: :url) -> void

                        def to_hash: -> Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::ToolResult::Content::UnionMember1::Image::Source::url
                      end

                      def self?.variants: -> [Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::ToolResult::Content::UnionMember1::Image::Source::Base64, Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::ToolResult::Content::UnionMember1::Image::Source::URL]
                    end

                    type cache_control = { type: :ephemeral }

                    class CacheControl < Sam::Internal::Type::BaseModel
                      attr_accessor type: :ephemeral

                      def initialize: (?type: :ephemeral) -> void

                      def to_hash: -> Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::ToolResult::Content::UnionMember1::Image::cache_control
                    end
                  end

                  def self?.variants: -> [Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::ToolResult::Content::UnionMember1::Text, Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::ToolResult::Content::UnionMember1::Image]
                end

                def self?.variants: -> [String, ::Array[Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::ToolResult::Content::union_member1]]

                UnionMember1Array: Sam::Internal::Type::Converter
              end
            end

            type document =
              {
                source: Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::source,
                type: :document,
                cache_control: Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::CacheControl?,
                citations: Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Citations,
                context: String?,
                title: String?
              }

            class Document < Sam::Internal::Type::BaseModel
              attr_accessor source: Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::source

              attr_accessor type: :document

              attr_accessor cache_control: Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::CacheControl?

              attr_reader citations: Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Citations?

              def citations=: (
                Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Citations
              ) -> Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Citations

              attr_accessor context: String?

              attr_accessor title: String?

              def initialize: (
                source: Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::source,
                ?cache_control: Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::CacheControl?,
                ?citations: Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Citations,
                ?context: String?,
                ?title: String?,
                ?type: :document
              ) -> void

              def to_hash: -> Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::document

              type source =
                Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Source::Base64
                | Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Source::Text
                | Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Source::Content
                | Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Source::URL

              module Source
                extend Sam::Internal::Type::Union

                type base64 =
                  {
                    data: String,
                    media_type: :"application/pdf",
                    type: :base64
                  }

                class Base64 < Sam::Internal::Type::BaseModel
                  attr_accessor data: String

                  attr_accessor media_type: :"application/pdf"

                  attr_accessor type: :base64

                  def initialize: (
                    data: String,
                    ?media_type: :"application/pdf",
                    ?type: :base64
                  ) -> void

                  def to_hash: -> Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Source::base64
                end

                type text =
                  { data: String, media_type: :"text/plain", type: :text }

                class Text < Sam::Internal::Type::BaseModel
                  attr_accessor data: String

                  attr_accessor media_type: :"text/plain"

                  attr_accessor type: :text

                  def initialize: (
                    data: String,
                    ?media_type: :"text/plain",
                    ?type: :text
                  ) -> void

                  def to_hash: -> Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Source::text
                end

                type content =
                  {
                    content: Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Source::Content::content,
                    type: :content
                  }

                class Content < Sam::Internal::Type::BaseModel
                  attr_accessor content: Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Source::Content::content

                  attr_accessor type: :content

                  def initialize: (
                    content: Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Source::Content::content,
                    ?type: :content
                  ) -> void

                  def to_hash: -> Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Source::content

                  type content =
                    String
                    | ::Array[Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Source::Content::Content::union_member1]

                  module Content
                    extend Sam::Internal::Type::Union

                    type union_member1 =
                      Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Source::Content::Content::UnionMember1::Text
                      | Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Source::Content::Content::UnionMember1::Image

                    module UnionMember1
                      extend Sam::Internal::Type::Union

                      type text =
                        {
                          text: String,
                          type: :text,
                          cache_control: Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Source::Content::Content::UnionMember1::Text::CacheControl?,
                          citations: ::Array[Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Source::Content::Content::UnionMember1::Text::citation]?
                        }

                      class Text < Sam::Internal::Type::BaseModel
                        attr_accessor text: String

                        attr_accessor type: :text

                        attr_accessor cache_control: Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Source::Content::Content::UnionMember1::Text::CacheControl?

                        attr_accessor citations: ::Array[Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Source::Content::Content::UnionMember1::Text::citation]?

                        def initialize: (
                          text: String,
                          ?cache_control: Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Source::Content::Content::UnionMember1::Text::CacheControl?,
                          ?citations: ::Array[Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Source::Content::Content::UnionMember1::Text::citation]?,
                          ?type: :text
                        ) -> void

                        def to_hash: -> Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Source::Content::Content::UnionMember1::text

                        type cache_control = { type: :ephemeral }

                        class CacheControl < Sam::Internal::Type::BaseModel
                          attr_accessor type: :ephemeral

                          def initialize: (?type: :ephemeral) -> void

                          def to_hash: -> Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Source::Content::Content::UnionMember1::Text::cache_control
                        end

                        type citation =
                          Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Source::Content::Content::UnionMember1::Text::Citation::CharLocation
                          | Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Source::Content::Content::UnionMember1::Text::Citation::PageLocation
                          | Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Source::Content::Content::UnionMember1::Text::Citation::ContentBlockLocation

                        module Citation
                          extend Sam::Internal::Type::Union

                          type char_location =
                            {
                              cited_text: String,
                              document_index: Integer,
                              document_title: String?,
                              end_char_index: Integer,
                              start_char_index: Integer,
                              type: :char_location
                            }

                          class CharLocation < Sam::Internal::Type::BaseModel
                            attr_accessor cited_text: String

                            attr_accessor document_index: Integer

                            attr_accessor document_title: String?

                            attr_accessor end_char_index: Integer

                            attr_accessor start_char_index: Integer

                            attr_accessor type: :char_location

                            def initialize: (
                              cited_text: String,
                              document_index: Integer,
                              document_title: String?,
                              end_char_index: Integer,
                              start_char_index: Integer,
                              ?type: :char_location
                            ) -> void

                            def to_hash: -> Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Source::Content::Content::UnionMember1::Text::Citation::char_location
                          end

                          type page_location =
                            {
                              cited_text: String,
                              document_index: Integer,
                              document_title: String?,
                              end_page_number: Integer,
                              start_page_number: Integer,
                              type: :page_location
                            }

                          class PageLocation < Sam::Internal::Type::BaseModel
                            attr_accessor cited_text: String

                            attr_accessor document_index: Integer

                            attr_accessor document_title: String?

                            attr_accessor end_page_number: Integer

                            attr_accessor start_page_number: Integer

                            attr_accessor type: :page_location

                            def initialize: (
                              cited_text: String,
                              document_index: Integer,
                              document_title: String?,
                              end_page_number: Integer,
                              start_page_number: Integer,
                              ?type: :page_location
                            ) -> void

                            def to_hash: -> Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Source::Content::Content::UnionMember1::Text::Citation::page_location
                          end

                          type content_block_location =
                            {
                              cited_text: String,
                              document_index: Integer,
                              document_title: String?,
                              end_block_index: Integer,
                              start_block_index: Integer,
                              type: :content_block_location
                            }

                          class ContentBlockLocation < Sam::Internal::Type::BaseModel
                            attr_accessor cited_text: String

                            attr_accessor document_index: Integer

                            attr_accessor document_title: String?

                            attr_accessor end_block_index: Integer

                            attr_accessor start_block_index: Integer

                            attr_accessor type: :content_block_location

                            def initialize: (
                              cited_text: String,
                              document_index: Integer,
                              document_title: String?,
                              end_block_index: Integer,
                              start_block_index: Integer,
                              ?type: :content_block_location
                            ) -> void

                            def to_hash: -> Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Source::Content::Content::UnionMember1::Text::Citation::content_block_location
                          end

                          def self?.variants: -> [Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Source::Content::Content::UnionMember1::Text::Citation::CharLocation, Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Source::Content::Content::UnionMember1::Text::Citation::PageLocation, Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Source::Content::Content::UnionMember1::Text::Citation::ContentBlockLocation]
                        end
                      end

                      type image =
                        {
                          source: Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Source::Content::Content::UnionMember1::Image::source,
                          type: :image,
                          cache_control: Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Source::Content::Content::UnionMember1::Image::CacheControl?
                        }

                      class Image < Sam::Internal::Type::BaseModel
                        attr_accessor source: Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Source::Content::Content::UnionMember1::Image::source

                        attr_accessor type: :image

                        attr_accessor cache_control: Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Source::Content::Content::UnionMember1::Image::CacheControl?

                        def initialize: (
                          source: Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Source::Content::Content::UnionMember1::Image::source,
                          ?cache_control: Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Source::Content::Content::UnionMember1::Image::CacheControl?,
                          ?type: :image
                        ) -> void

                        def to_hash: -> Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Source::Content::Content::UnionMember1::image

                        type source =
                          Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Source::Content::Content::UnionMember1::Image::Source::Base64
                          | Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Source::Content::Content::UnionMember1::Image::Source::URL

                        module Source
                          extend Sam::Internal::Type::Union

                          type base64 =
                            {
                              data: String,
                              media_type: Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Source::Content::Content::UnionMember1::Image::Source::Base64::media_type,
                              type: :base64
                            }

                          class Base64 < Sam::Internal::Type::BaseModel
                            attr_accessor data: String

                            attr_accessor media_type: Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Source::Content::Content::UnionMember1::Image::Source::Base64::media_type

                            attr_accessor type: :base64

                            def initialize: (
                              data: String,
                              media_type: Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Source::Content::Content::UnionMember1::Image::Source::Base64::media_type,
                              ?type: :base64
                            ) -> void

                            def to_hash: -> Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Source::Content::Content::UnionMember1::Image::Source::base64

                            type media_type =
                              :"image/jpeg"
                              | :"image/png"
                              | :"image/gif"
                              | :"image/webp"

                            module MediaType
                              extend Sam::Internal::Type::Enum

                              IMAGE_JPEG: :"image/jpeg"
                              IMAGE_PNG: :"image/png"
                              IMAGE_GIF: :"image/gif"
                              IMAGE_WEBP: :"image/webp"

                              def self?.values: -> ::Array[Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Source::Content::Content::UnionMember1::Image::Source::Base64::media_type]
                            end
                          end

                          type url = { type: :url, url: String }

                          class URL < Sam::Internal::Type::BaseModel
                            attr_accessor type: :url

                            attr_accessor url: String

                            def initialize: (url: String, ?type: :url) -> void

                            def to_hash: -> Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Source::Content::Content::UnionMember1::Image::Source::url
                          end

                          def self?.variants: -> [Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Source::Content::Content::UnionMember1::Image::Source::Base64, Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Source::Content::Content::UnionMember1::Image::Source::URL]
                        end

                        type cache_control = { type: :ephemeral }

                        class CacheControl < Sam::Internal::Type::BaseModel
                          attr_accessor type: :ephemeral

                          def initialize: (?type: :ephemeral) -> void

                          def to_hash: -> Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Source::Content::Content::UnionMember1::Image::cache_control
                        end
                      end

                      def self?.variants: -> [Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Source::Content::Content::UnionMember1::Text, Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Source::Content::Content::UnionMember1::Image]
                    end

                    def self?.variants: -> [String, ::Array[Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Source::Content::Content::union_member1]]

                    UnionMember1Array: Sam::Internal::Type::Converter
                  end
                end

                type url = { type: :url, url: String }

                class URL < Sam::Internal::Type::BaseModel
                  attr_accessor type: :url

                  attr_accessor url: String

                  def initialize: (url: String, ?type: :url) -> void

                  def to_hash: -> Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Source::url
                end

                def self?.variants: -> [Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Source::Base64, Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Source::Text, Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Source::Content, Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::Source::URL]
              end

              type cache_control = { type: :ephemeral }

              class CacheControl < Sam::Internal::Type::BaseModel
                attr_accessor type: :ephemeral

                def initialize: (?type: :ephemeral) -> void

                def to_hash: -> Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::cache_control
              end

              type citations = { enabled: bool }

              class Citations < Sam::Internal::Type::BaseModel
                attr_reader enabled: bool?

                def enabled=: (bool) -> bool

                def initialize: (?enabled: bool) -> void

                def to_hash: -> Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document::citations
              end
            end

            type thinking =
              { signature: String, thinking: String, type: :thinking }

            class Thinking < Sam::Internal::Type::BaseModel
              attr_accessor signature: String

              attr_accessor thinking: String

              attr_accessor type: :thinking

              def initialize: (
                signature: String,
                thinking: String,
                ?type: :thinking
              ) -> void

              def to_hash: -> Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::thinking
            end

            type redacted_thinking = { data: String, type: :redacted_thinking }

            class RedactedThinking < Sam::Internal::Type::BaseModel
              attr_accessor data: String

              attr_accessor type: :redacted_thinking

              def initialize: (data: String, ?type: :redacted_thinking) -> void

              def to_hash: -> Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::redacted_thinking
            end

            def self?.variants: -> [Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Text, Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Image, Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::ToolUse, Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::ToolResult, Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Document, Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::Thinking, Sam::Models::MessageCountTokensBetaParams::Message::Content::UnionMember1::RedactedThinking]
          end

          def self?.variants: -> [String, ::Array[Sam::Models::MessageCountTokensBetaParams::Message::Content::union_member1]]

          UnionMember1Array: Sam::Internal::Type::Converter
        end

        type role = :user | :assistant

        module Role
          extend Sam::Internal::Type::Enum

          USER: :user
          ASSISTANT: :assistant

          def self?.values: -> ::Array[Sam::Models::MessageCountTokensBetaParams::Message::role]
        end
      end

      type system_ =
        String
        | ::Array[Sam::Models::MessageCountTokensBetaParams::System::UnionMember1]

      module System
        extend Sam::Internal::Type::Union

        type union_member1 =
          {
            text: String,
            type: :text,
            cache_control: Sam::Models::MessageCountTokensBetaParams::System::UnionMember1::CacheControl?,
            citations: ::Array[Sam::Models::MessageCountTokensBetaParams::System::UnionMember1::citation]?
          }

        class UnionMember1 < Sam::Internal::Type::BaseModel
          attr_accessor text: String

          attr_accessor type: :text

          attr_accessor cache_control: Sam::Models::MessageCountTokensBetaParams::System::UnionMember1::CacheControl?

          attr_accessor citations: ::Array[Sam::Models::MessageCountTokensBetaParams::System::UnionMember1::citation]?

          def initialize: (
            text: String,
            ?cache_control: Sam::Models::MessageCountTokensBetaParams::System::UnionMember1::CacheControl?,
            ?citations: ::Array[Sam::Models::MessageCountTokensBetaParams::System::UnionMember1::citation]?,
            ?type: :text
          ) -> void

          def to_hash: -> Sam::Models::MessageCountTokensBetaParams::System::union_member1

          type cache_control = { type: :ephemeral }

          class CacheControl < Sam::Internal::Type::BaseModel
            attr_accessor type: :ephemeral

            def initialize: (?type: :ephemeral) -> void

            def to_hash: -> Sam::Models::MessageCountTokensBetaParams::System::UnionMember1::cache_control
          end

          type citation =
            Sam::Models::MessageCountTokensBetaParams::System::UnionMember1::Citation::CharLocation
            | Sam::Models::MessageCountTokensBetaParams::System::UnionMember1::Citation::PageLocation
            | Sam::Models::MessageCountTokensBetaParams::System::UnionMember1::Citation::ContentBlockLocation

          module Citation
            extend Sam::Internal::Type::Union

            type char_location =
              {
                cited_text: String,
                document_index: Integer,
                document_title: String?,
                end_char_index: Integer,
                start_char_index: Integer,
                type: :char_location
              }

            class CharLocation < Sam::Internal::Type::BaseModel
              attr_accessor cited_text: String

              attr_accessor document_index: Integer

              attr_accessor document_title: String?

              attr_accessor end_char_index: Integer

              attr_accessor start_char_index: Integer

              attr_accessor type: :char_location

              def initialize: (
                cited_text: String,
                document_index: Integer,
                document_title: String?,
                end_char_index: Integer,
                start_char_index: Integer,
                ?type: :char_location
              ) -> void

              def to_hash: -> Sam::Models::MessageCountTokensBetaParams::System::UnionMember1::Citation::char_location
            end

            type page_location =
              {
                cited_text: String,
                document_index: Integer,
                document_title: String?,
                end_page_number: Integer,
                start_page_number: Integer,
                type: :page_location
              }

            class PageLocation < Sam::Internal::Type::BaseModel
              attr_accessor cited_text: String

              attr_accessor document_index: Integer

              attr_accessor document_title: String?

              attr_accessor end_page_number: Integer

              attr_accessor start_page_number: Integer

              attr_accessor type: :page_location

              def initialize: (
                cited_text: String,
                document_index: Integer,
                document_title: String?,
                end_page_number: Integer,
                start_page_number: Integer,
                ?type: :page_location
              ) -> void

              def to_hash: -> Sam::Models::MessageCountTokensBetaParams::System::UnionMember1::Citation::page_location
            end

            type content_block_location =
              {
                cited_text: String,
                document_index: Integer,
                document_title: String?,
                end_block_index: Integer,
                start_block_index: Integer,
                type: :content_block_location
              }

            class ContentBlockLocation < Sam::Internal::Type::BaseModel
              attr_accessor cited_text: String

              attr_accessor document_index: Integer

              attr_accessor document_title: String?

              attr_accessor end_block_index: Integer

              attr_accessor start_block_index: Integer

              attr_accessor type: :content_block_location

              def initialize: (
                cited_text: String,
                document_index: Integer,
                document_title: String?,
                end_block_index: Integer,
                start_block_index: Integer,
                ?type: :content_block_location
              ) -> void

              def to_hash: -> Sam::Models::MessageCountTokensBetaParams::System::UnionMember1::Citation::content_block_location
            end

            def self?.variants: -> [Sam::Models::MessageCountTokensBetaParams::System::UnionMember1::Citation::CharLocation, Sam::Models::MessageCountTokensBetaParams::System::UnionMember1::Citation::PageLocation, Sam::Models::MessageCountTokensBetaParams::System::UnionMember1::Citation::ContentBlockLocation]
          end
        end

        def self?.variants: -> [String, ::Array[Sam::Models::MessageCountTokensBetaParams::System::UnionMember1]]

        UnionMember1Array: Sam::Internal::Type::Converter
      end

      type thinking =
        Sam::Models::MessageCountTokensBetaParams::Thinking::Enabled
        | Sam::Models::MessageCountTokensBetaParams::Thinking::Disabled

      module Thinking
        extend Sam::Internal::Type::Union

        type enabled = { budget_tokens: Integer, type: :enabled }

        class Enabled < Sam::Internal::Type::BaseModel
          attr_accessor budget_tokens: Integer

          attr_accessor type: :enabled

          def initialize: (budget_tokens: Integer, ?type: :enabled) -> void

          def to_hash: -> Sam::Models::MessageCountTokensBetaParams::Thinking::enabled
        end

        type disabled = { type: :disabled }

        class Disabled < Sam::Internal::Type::BaseModel
          attr_accessor type: :disabled

          def initialize: (?type: :disabled) -> void

          def to_hash: -> Sam::Models::MessageCountTokensBetaParams::Thinking::disabled
        end

        def self?.variants: -> [Sam::Models::MessageCountTokensBetaParams::Thinking::Enabled, Sam::Models::MessageCountTokensBetaParams::Thinking::Disabled]
      end

      type tool_choice =
        Sam::Models::MessageCountTokensBetaParams::ToolChoice::Auto
        | Sam::Models::MessageCountTokensBetaParams::ToolChoice::Any
        | Sam::Models::MessageCountTokensBetaParams::ToolChoice::Tool
        | Sam::Models::MessageCountTokensBetaParams::ToolChoice::None

      module ToolChoice
        extend Sam::Internal::Type::Union

        type auto = { type: :auto, disable_parallel_tool_use: bool }

        class Auto < Sam::Internal::Type::BaseModel
          attr_accessor type: :auto

          attr_reader disable_parallel_tool_use: bool?

          def disable_parallel_tool_use=: (bool) -> bool

          def initialize: (
            ?disable_parallel_tool_use: bool,
            ?type: :auto
          ) -> void

          def to_hash: -> Sam::Models::MessageCountTokensBetaParams::ToolChoice::auto
        end

        type any = { type: :any, disable_parallel_tool_use: bool }

        class Any < Sam::Internal::Type::BaseModel
          attr_accessor type: :any

          attr_reader disable_parallel_tool_use: bool?

          def disable_parallel_tool_use=: (bool) -> bool

          def initialize: (
            ?disable_parallel_tool_use: bool,
            ?type: :any
          ) -> void

          def to_hash: -> Sam::Models::MessageCountTokensBetaParams::ToolChoice::any
        end

        type tool =
          { name: String, type: :tool, disable_parallel_tool_use: bool }

        class Tool < Sam::Internal::Type::BaseModel
          attr_accessor name: String

          attr_accessor type: :tool

          attr_reader disable_parallel_tool_use: bool?

          def disable_parallel_tool_use=: (bool) -> bool

          def initialize: (
            name: String,
            ?disable_parallel_tool_use: bool,
            ?type: :tool
          ) -> void

          def to_hash: -> Sam::Models::MessageCountTokensBetaParams::ToolChoice::tool
        end

        type none = { type: :none }

        class None < Sam::Internal::Type::BaseModel
          attr_accessor type: :none

          def initialize: (?type: :none) -> void

          def to_hash: -> Sam::Models::MessageCountTokensBetaParams::ToolChoice::none
        end

        def self?.variants: -> [Sam::Models::MessageCountTokensBetaParams::ToolChoice::Auto, Sam::Models::MessageCountTokensBetaParams::ToolChoice::Any, Sam::Models::MessageCountTokensBetaParams::ToolChoice::Tool, Sam::Models::MessageCountTokensBetaParams::ToolChoice::None]
      end

      type tool =
        Sam::Models::MessageCountTokensBetaParams::Tool::BetaTool
        | Sam::Models::MessageCountTokensBetaParams::Tool::BetaComputerUseTool20241022
        | Sam::Models::MessageCountTokensBetaParams::Tool::BetaBashTool20241022
        | Sam::Models::MessageCountTokensBetaParams::Tool::BetaTextEditor20241022
        | Sam::Models::MessageCountTokensBetaParams::Tool::BetaComputerUseTool20250124
        | Sam::Models::MessageCountTokensBetaParams::Tool::BetaBashTool20250124
        | Sam::Models::MessageCountTokensBetaParams::Tool::BetaTextEditor20250124

      module Tool
        extend Sam::Internal::Type::Union

        type beta_tool =
          {
            input_schema: Sam::Models::MessageCountTokensBetaParams::Tool::BetaTool::InputSchema,
            name: String,
            cache_control: Sam::Models::MessageCountTokensBetaParams::Tool::BetaTool::CacheControl?,
            description: String,
            type: Sam::Models::MessageCountTokensBetaParams::Tool::BetaTool::type_?
          }

        class BetaTool < Sam::Internal::Type::BaseModel
          attr_accessor input_schema: Sam::Models::MessageCountTokensBetaParams::Tool::BetaTool::InputSchema

          attr_accessor name: String

          attr_accessor cache_control: Sam::Models::MessageCountTokensBetaParams::Tool::BetaTool::CacheControl?

          attr_reader description: String?

          def description=: (String) -> String

          attr_accessor type: Sam::Models::MessageCountTokensBetaParams::Tool::BetaTool::type_?

          def initialize: (
            input_schema: Sam::Models::MessageCountTokensBetaParams::Tool::BetaTool::InputSchema,
            name: String,
            ?cache_control: Sam::Models::MessageCountTokensBetaParams::Tool::BetaTool::CacheControl?,
            ?description: String,
            ?type: Sam::Models::MessageCountTokensBetaParams::Tool::BetaTool::type_?
          ) -> void

          def to_hash: -> Sam::Models::MessageCountTokensBetaParams::Tool::beta_tool

          type input_schema = { type: :object, properties: top? }

          class InputSchema < Sam::Internal::Type::BaseModel
            attr_accessor type: :object

            attr_accessor properties: top?

            def initialize: (?properties: top?, ?type: :object) -> void

            def to_hash: -> Sam::Models::MessageCountTokensBetaParams::Tool::BetaTool::input_schema
          end

          type cache_control = { type: :ephemeral }

          class CacheControl < Sam::Internal::Type::BaseModel
            attr_accessor type: :ephemeral

            def initialize: (?type: :ephemeral) -> void

            def to_hash: -> Sam::Models::MessageCountTokensBetaParams::Tool::BetaTool::cache_control
          end

          type type_ = :custom

          module Type
            extend Sam::Internal::Type::Enum

            CUSTOM: :custom

            def self?.values: -> ::Array[Sam::Models::MessageCountTokensBetaParams::Tool::BetaTool::type_]
          end
        end

        type beta_computer_use_tool20241022 =
          {
            display_height_px: Integer,
            display_width_px: Integer,
            name: :computer,
            type: :computer_20241022,
            cache_control: Sam::Models::MessageCountTokensBetaParams::Tool::BetaComputerUseTool20241022::CacheControl?,
            display_number: Integer?
          }

        class BetaComputerUseTool20241022 < Sam::Internal::Type::BaseModel
          attr_accessor display_height_px: Integer

          attr_accessor display_width_px: Integer

          attr_accessor name: :computer

          attr_accessor type: :computer_20241022

          attr_accessor cache_control: Sam::Models::MessageCountTokensBetaParams::Tool::BetaComputerUseTool20241022::CacheControl?

          attr_accessor display_number: Integer?

          def initialize: (
            display_height_px: Integer,
            display_width_px: Integer,
            ?cache_control: Sam::Models::MessageCountTokensBetaParams::Tool::BetaComputerUseTool20241022::CacheControl?,
            ?display_number: Integer?,
            ?name: :computer,
            ?type: :computer_20241022
          ) -> void

          def to_hash: -> Sam::Models::MessageCountTokensBetaParams::Tool::beta_computer_use_tool20241022

          type cache_control = { type: :ephemeral }

          class CacheControl < Sam::Internal::Type::BaseModel
            attr_accessor type: :ephemeral

            def initialize: (?type: :ephemeral) -> void

            def to_hash: -> Sam::Models::MessageCountTokensBetaParams::Tool::BetaComputerUseTool20241022::cache_control
          end
        end

        type beta_bash_tool20241022 =
          {
            name: :bash,
            type: :bash_20241022,
            cache_control: Sam::Models::MessageCountTokensBetaParams::Tool::BetaBashTool20241022::CacheControl?
          }

        class BetaBashTool20241022 < Sam::Internal::Type::BaseModel
          attr_accessor name: :bash

          attr_accessor type: :bash_20241022

          attr_accessor cache_control: Sam::Models::MessageCountTokensBetaParams::Tool::BetaBashTool20241022::CacheControl?

          def initialize: (
            ?cache_control: Sam::Models::MessageCountTokensBetaParams::Tool::BetaBashTool20241022::CacheControl?,
            ?name: :bash,
            ?type: :bash_20241022
          ) -> void

          def to_hash: -> Sam::Models::MessageCountTokensBetaParams::Tool::beta_bash_tool20241022

          type cache_control = { type: :ephemeral }

          class CacheControl < Sam::Internal::Type::BaseModel
            attr_accessor type: :ephemeral

            def initialize: (?type: :ephemeral) -> void

            def to_hash: -> Sam::Models::MessageCountTokensBetaParams::Tool::BetaBashTool20241022::cache_control
          end
        end

        type beta_text_editor20241022 =
          {
            name: :str_replace_editor,
            type: :text_editor_20241022,
            cache_control: Sam::Models::MessageCountTokensBetaParams::Tool::BetaTextEditor20241022::CacheControl?
          }

        class BetaTextEditor20241022 < Sam::Internal::Type::BaseModel
          attr_accessor name: :str_replace_editor

          attr_accessor type: :text_editor_20241022

          attr_accessor cache_control: Sam::Models::MessageCountTokensBetaParams::Tool::BetaTextEditor20241022::CacheControl?

          def initialize: (
            ?cache_control: Sam::Models::MessageCountTokensBetaParams::Tool::BetaTextEditor20241022::CacheControl?,
            ?name: :str_replace_editor,
            ?type: :text_editor_20241022
          ) -> void

          def to_hash: -> Sam::Models::MessageCountTokensBetaParams::Tool::beta_text_editor20241022

          type cache_control = { type: :ephemeral }

          class CacheControl < Sam::Internal::Type::BaseModel
            attr_accessor type: :ephemeral

            def initialize: (?type: :ephemeral) -> void

            def to_hash: -> Sam::Models::MessageCountTokensBetaParams::Tool::BetaTextEditor20241022::cache_control
          end
        end

        type beta_computer_use_tool20250124 =
          {
            display_height_px: Integer,
            display_width_px: Integer,
            name: :computer,
            type: :computer_20250124,
            cache_control: Sam::Models::MessageCountTokensBetaParams::Tool::BetaComputerUseTool20250124::CacheControl?,
            display_number: Integer?
          }

        class BetaComputerUseTool20250124 < Sam::Internal::Type::BaseModel
          attr_accessor display_height_px: Integer

          attr_accessor display_width_px: Integer

          attr_accessor name: :computer

          attr_accessor type: :computer_20250124

          attr_accessor cache_control: Sam::Models::MessageCountTokensBetaParams::Tool::BetaComputerUseTool20250124::CacheControl?

          attr_accessor display_number: Integer?

          def initialize: (
            display_height_px: Integer,
            display_width_px: Integer,
            ?cache_control: Sam::Models::MessageCountTokensBetaParams::Tool::BetaComputerUseTool20250124::CacheControl?,
            ?display_number: Integer?,
            ?name: :computer,
            ?type: :computer_20250124
          ) -> void

          def to_hash: -> Sam::Models::MessageCountTokensBetaParams::Tool::beta_computer_use_tool20250124

          type cache_control = { type: :ephemeral }

          class CacheControl < Sam::Internal::Type::BaseModel
            attr_accessor type: :ephemeral

            def initialize: (?type: :ephemeral) -> void

            def to_hash: -> Sam::Models::MessageCountTokensBetaParams::Tool::BetaComputerUseTool20250124::cache_control
          end
        end

        type beta_bash_tool20250124 =
          {
            name: :bash,
            type: :bash_20250124,
            cache_control: Sam::Models::MessageCountTokensBetaParams::Tool::BetaBashTool20250124::CacheControl?
          }

        class BetaBashTool20250124 < Sam::Internal::Type::BaseModel
          attr_accessor name: :bash

          attr_accessor type: :bash_20250124

          attr_accessor cache_control: Sam::Models::MessageCountTokensBetaParams::Tool::BetaBashTool20250124::CacheControl?

          def initialize: (
            ?cache_control: Sam::Models::MessageCountTokensBetaParams::Tool::BetaBashTool20250124::CacheControl?,
            ?name: :bash,
            ?type: :bash_20250124
          ) -> void

          def to_hash: -> Sam::Models::MessageCountTokensBetaParams::Tool::beta_bash_tool20250124

          type cache_control = { type: :ephemeral }

          class CacheControl < Sam::Internal::Type::BaseModel
            attr_accessor type: :ephemeral

            def initialize: (?type: :ephemeral) -> void

            def to_hash: -> Sam::Models::MessageCountTokensBetaParams::Tool::BetaBashTool20250124::cache_control
          end
        end

        type beta_text_editor20250124 =
          {
            name: :str_replace_editor,
            type: :text_editor_20250124,
            cache_control: Sam::Models::MessageCountTokensBetaParams::Tool::BetaTextEditor20250124::CacheControl?
          }

        class BetaTextEditor20250124 < Sam::Internal::Type::BaseModel
          attr_accessor name: :str_replace_editor

          attr_accessor type: :text_editor_20250124

          attr_accessor cache_control: Sam::Models::MessageCountTokensBetaParams::Tool::BetaTextEditor20250124::CacheControl?

          def initialize: (
            ?cache_control: Sam::Models::MessageCountTokensBetaParams::Tool::BetaTextEditor20250124::CacheControl?,
            ?name: :str_replace_editor,
            ?type: :text_editor_20250124
          ) -> void

          def to_hash: -> Sam::Models::MessageCountTokensBetaParams::Tool::beta_text_editor20250124

          type cache_control = { type: :ephemeral }

          class CacheControl < Sam::Internal::Type::BaseModel
            attr_accessor type: :ephemeral

            def initialize: (?type: :ephemeral) -> void

            def to_hash: -> Sam::Models::MessageCountTokensBetaParams::Tool::BetaTextEditor20250124::cache_control
          end
        end

        def self?.variants: -> [Sam::Models::MessageCountTokensBetaParams::Tool::BetaTool, Sam::Models::MessageCountTokensBetaParams::Tool::BetaComputerUseTool20241022, Sam::Models::MessageCountTokensBetaParams::Tool::BetaBashTool20241022, Sam::Models::MessageCountTokensBetaParams::Tool::BetaTextEditor20241022, Sam::Models::MessageCountTokensBetaParams::Tool::BetaComputerUseTool20250124, Sam::Models::MessageCountTokensBetaParams::Tool::BetaBashTool20250124, Sam::Models::MessageCountTokensBetaParams::Tool::BetaTextEditor20250124]
      end
    end
  end
end
