module Sam
  module Models
    type message_create_response =
      {
        id: String,
        content: ::Array[Sam::Models::MessageCreateResponse::content],
        model: String,
        role: :assistant,
        stop_reason: Sam::Models::MessageCreateResponse::stop_reason?,
        stop_sequence: String?,
        type: :message,
        usage: Sam::Models::MessageCreateResponse::Usage
      }

    class MessageCreateResponse < Sam::BaseModel
      attr_accessor id: String

      attr_accessor content: ::Array[Sam::Models::MessageCreateResponse::content]

      attr_accessor model: String

      attr_accessor role: :assistant

      attr_accessor stop_reason: Sam::Models::MessageCreateResponse::stop_reason?

      attr_accessor stop_sequence: String?

      attr_accessor type: :message

      attr_accessor usage: Sam::Models::MessageCreateResponse::Usage

      def initialize:
        (
          id: String,
          content: ::Array[Sam::Models::MessageCreateResponse::content],
          model: String,
          stop_reason: Sam::Models::MessageCreateResponse::stop_reason?,
          stop_sequence: String?,
          usage: Sam::Models::MessageCreateResponse::Usage,
          role: :assistant,
          type: :message
        ) -> void
        | (?Sam::Models::message_create_response | Sam::BaseModel data) -> void

      def to_hash: -> Sam::Models::message_create_response

      type content =
        Sam::Models::MessageCreateResponse::Content::ResponseTextBlock
        | Sam::Models::MessageCreateResponse::Content::ResponseToolUseBlock
        | Sam::Models::MessageCreateResponse::Content::ResponseThinkingBlock
        | Sam::Models::MessageCreateResponse::Content::ResponseRedactedThinkingBlock

      class Content < Sam::Union
        type response_text_block =
          {
            citations: ::Array[Sam::Models::MessageCreateResponse::Content::ResponseTextBlock::citation]?,
            text: String,
            type: :text
          }

        class ResponseTextBlock < Sam::BaseModel
          attr_accessor citations: ::Array[Sam::Models::MessageCreateResponse::Content::ResponseTextBlock::citation]?

          attr_accessor text: String

          attr_accessor type: :text

          def initialize:
            (
              citations: ::Array[Sam::Models::MessageCreateResponse::Content::ResponseTextBlock::citation]?,
              text: String,
              type: :text
            ) -> void
            | (
              ?Sam::Models::MessageCreateResponse::Content::response_text_block
              | Sam::BaseModel data
            ) -> void

          def to_hash: -> Sam::Models::MessageCreateResponse::Content::response_text_block

          type citation =
            Sam::Models::MessageCreateResponse::Content::ResponseTextBlock::Citation::ResponseCharLocationCitation
            | Sam::Models::MessageCreateResponse::Content::ResponseTextBlock::Citation::ResponsePageLocationCitation
            | Sam::Models::MessageCreateResponse::Content::ResponseTextBlock::Citation::ResponseContentBlockLocationCitation

          class Citation < Sam::Union
            type response_char_location_citation =
              {
                cited_text: String,
                document_index: Integer,
                document_title: String?,
                end_char_index: Integer,
                start_char_index: Integer,
                type: :char_location
              }

            class ResponseCharLocationCitation < Sam::BaseModel
              attr_accessor cited_text: String

              attr_accessor document_index: Integer

              attr_accessor document_title: String?

              attr_accessor end_char_index: Integer

              attr_accessor start_char_index: Integer

              attr_accessor type: :char_location

              def initialize:
                (
                  cited_text: String,
                  document_index: Integer,
                  document_title: String?,
                  end_char_index: Integer,
                  start_char_index: Integer,
                  type: :char_location
                ) -> void
                | (
                  ?Sam::Models::MessageCreateResponse::Content::ResponseTextBlock::Citation::response_char_location_citation
                  | Sam::BaseModel data
                ) -> void

              def to_hash: -> Sam::Models::MessageCreateResponse::Content::ResponseTextBlock::Citation::response_char_location_citation
            end

            type response_page_location_citation =
              {
                cited_text: String,
                document_index: Integer,
                document_title: String?,
                end_page_number: Integer,
                start_page_number: Integer,
                type: :page_location
              }

            class ResponsePageLocationCitation < Sam::BaseModel
              attr_accessor cited_text: String

              attr_accessor document_index: Integer

              attr_accessor document_title: String?

              attr_accessor end_page_number: Integer

              attr_accessor start_page_number: Integer

              attr_accessor type: :page_location

              def initialize:
                (
                  cited_text: String,
                  document_index: Integer,
                  document_title: String?,
                  end_page_number: Integer,
                  start_page_number: Integer,
                  type: :page_location
                ) -> void
                | (
                  ?Sam::Models::MessageCreateResponse::Content::ResponseTextBlock::Citation::response_page_location_citation
                  | Sam::BaseModel data
                ) -> void

              def to_hash: -> Sam::Models::MessageCreateResponse::Content::ResponseTextBlock::Citation::response_page_location_citation
            end

            type response_content_block_location_citation =
              {
                cited_text: String,
                document_index: Integer,
                document_title: String?,
                end_block_index: Integer,
                start_block_index: Integer,
                type: :content_block_location
              }

            class ResponseContentBlockLocationCitation < Sam::BaseModel
              attr_accessor cited_text: String

              attr_accessor document_index: Integer

              attr_accessor document_title: String?

              attr_accessor end_block_index: Integer

              attr_accessor start_block_index: Integer

              attr_accessor type: :content_block_location

              def initialize:
                (
                  cited_text: String,
                  document_index: Integer,
                  document_title: String?,
                  end_block_index: Integer,
                  start_block_index: Integer,
                  type: :content_block_location
                ) -> void
                | (
                  ?Sam::Models::MessageCreateResponse::Content::ResponseTextBlock::Citation::response_content_block_location_citation
                  | Sam::BaseModel data
                ) -> void

              def to_hash: -> Sam::Models::MessageCreateResponse::Content::ResponseTextBlock::Citation::response_content_block_location_citation
            end

            private def self.variants: -> [[:char_location, Sam::Models::MessageCreateResponse::Content::ResponseTextBlock::Citation::ResponseCharLocationCitation], [:page_location, Sam::Models::MessageCreateResponse::Content::ResponseTextBlock::Citation::ResponsePageLocationCitation], [:content_block_location, Sam::Models::MessageCreateResponse::Content::ResponseTextBlock::Citation::ResponseContentBlockLocationCitation]]
          end
        end

        type response_tool_use_block =
          { id: String, input: top, name: String, type: :tool_use }

        class ResponseToolUseBlock < Sam::BaseModel
          attr_accessor id: String

          attr_accessor input: top

          attr_accessor name: String

          attr_accessor type: :tool_use

          def initialize:
            (id: String, input: top, name: String, type: :tool_use) -> void
            | (
              ?Sam::Models::MessageCreateResponse::Content::response_tool_use_block
              | Sam::BaseModel data
            ) -> void

          def to_hash: -> Sam::Models::MessageCreateResponse::Content::response_tool_use_block
        end

        type response_thinking_block =
          { signature: String, thinking: String, type: :thinking }

        class ResponseThinkingBlock < Sam::BaseModel
          attr_accessor signature: String

          attr_accessor thinking: String

          attr_accessor type: :thinking

          def initialize:
            (signature: String, thinking: String, type: :thinking) -> void
            | (
              ?Sam::Models::MessageCreateResponse::Content::response_thinking_block
              | Sam::BaseModel data
            ) -> void

          def to_hash: -> Sam::Models::MessageCreateResponse::Content::response_thinking_block
        end

        type response_redacted_thinking_block =
          { data: String, type: :redacted_thinking }

        class ResponseRedactedThinkingBlock < Sam::BaseModel
          attr_accessor data: String

          attr_accessor type: :redacted_thinking

          def initialize:
            (data: String, type: :redacted_thinking) -> void
            | (
              ?Sam::Models::MessageCreateResponse::Content::response_redacted_thinking_block
              | Sam::BaseModel data
            ) -> void

          def to_hash: -> Sam::Models::MessageCreateResponse::Content::response_redacted_thinking_block
        end

        private def self.variants: -> [[:text, Sam::Models::MessageCreateResponse::Content::ResponseTextBlock], [:tool_use, Sam::Models::MessageCreateResponse::Content::ResponseToolUseBlock], [:thinking, Sam::Models::MessageCreateResponse::Content::ResponseThinkingBlock], [:redacted_thinking, Sam::Models::MessageCreateResponse::Content::ResponseRedactedThinkingBlock]]
      end

      type stop_reason = :end_turn | :max_tokens | :stop_sequence | :tool_use

      class StopReason < Sam::Enum
        END_TURN: :end_turn
        MAX_TOKENS: :max_tokens
        STOP_SEQUENCE: :stop_sequence
        TOOL_USE: :tool_use

        def self.values: -> ::Array[Sam::Models::MessageCreateResponse::stop_reason]
      end

      type usage =
        {
          cache_creation_input_tokens: Integer?,
          cache_read_input_tokens: Integer?,
          input_tokens: Integer,
          output_tokens: Integer
        }

      class Usage < Sam::BaseModel
        attr_accessor cache_creation_input_tokens: Integer?

        attr_accessor cache_read_input_tokens: Integer?

        attr_accessor input_tokens: Integer

        attr_accessor output_tokens: Integer

        def initialize:
          (
            cache_creation_input_tokens: Integer?,
            cache_read_input_tokens: Integer?,
            input_tokens: Integer,
            output_tokens: Integer
          ) -> void
          | (
            ?Sam::Models::MessageCreateResponse::usage | Sam::BaseModel data
          ) -> void

        def to_hash: -> Sam::Models::MessageCreateResponse::usage
      end
    end
  end
end
