module Sam
  module Models
    type messages_beta_true_create_response =
      {
        id: String,
        content: ::Array[Sam::Models::MessagesBetaTrueCreateResponse::content],
        model: String,
        role: :assistant,
        stop_reason: Sam::Models::MessagesBetaTrueCreateResponse::stop_reason?,
        stop_sequence: String?,
        type: :message,
        usage: Sam::Models::MessagesBetaTrueCreateResponse::Usage
      }

    class MessagesBetaTrueCreateResponse < Sam::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor content: ::Array[Sam::Models::MessagesBetaTrueCreateResponse::content]

      attr_accessor model: String

      attr_accessor role: :assistant

      attr_accessor stop_reason: Sam::Models::MessagesBetaTrueCreateResponse::stop_reason?

      attr_accessor stop_sequence: String?

      attr_accessor type: :message

      attr_accessor usage: Sam::Models::MessagesBetaTrueCreateResponse::Usage

      def initialize: (
        id: String,
        content: ::Array[Sam::Models::MessagesBetaTrueCreateResponse::content],
        model: String,
        stop_reason: Sam::Models::MessagesBetaTrueCreateResponse::stop_reason?,
        stop_sequence: String?,
        usage: Sam::Models::MessagesBetaTrueCreateResponse::Usage,
        ?role: :assistant,
        ?type: :message
      ) -> void

      type content =
        Sam::Models::MessagesBetaTrueCreateResponse::Content::Text
        | Sam::Models::MessagesBetaTrueCreateResponse::Content::ToolUse
        | Sam::Models::MessagesBetaTrueCreateResponse::Content::Thinking
        | Sam::Models::MessagesBetaTrueCreateResponse::Content::RedactedThinking

      module Content
        extend Sam::Internal::Type::Union

        type text =
          {
            citations: ::Array[Sam::Models::MessagesBetaTrueCreateResponse::Content::Text::citation]?,
            text: String,
            type: :text
          }

        class Text < Sam::Internal::Type::BaseModel
          attr_accessor citations: ::Array[Sam::Models::MessagesBetaTrueCreateResponse::Content::Text::citation]?

          attr_accessor text: String

          attr_accessor type: :text

          def initialize: (
            citations: ::Array[Sam::Models::MessagesBetaTrueCreateResponse::Content::Text::citation]?,
            text: String,
            ?type: :text
          ) -> void

          type citation =
            Sam::Models::MessagesBetaTrueCreateResponse::Content::Text::Citation::CharLocation
            | Sam::Models::MessagesBetaTrueCreateResponse::Content::Text::Citation::PageLocation
            | Sam::Models::MessagesBetaTrueCreateResponse::Content::Text::Citation::ContentBlockLocation

          module Citation
            extend Sam::Internal::Type::Union

            type char_location =
              {
                cited_text: String,
                document_index: Integer,
                document_title: String?,
                end_char_index: Integer,
                start_char_index: Integer,
                type: :char_location
              }

            class CharLocation < Sam::Internal::Type::BaseModel
              attr_accessor cited_text: String

              attr_accessor document_index: Integer

              attr_accessor document_title: String?

              attr_accessor end_char_index: Integer

              attr_accessor start_char_index: Integer

              attr_accessor type: :char_location

              def initialize: (
                cited_text: String,
                document_index: Integer,
                document_title: String?,
                end_char_index: Integer,
                start_char_index: Integer,
                ?type: :char_location
              ) -> void
            end

            type page_location =
              {
                cited_text: String,
                document_index: Integer,
                document_title: String?,
                end_page_number: Integer,
                start_page_number: Integer,
                type: :page_location
              }

            class PageLocation < Sam::Internal::Type::BaseModel
              attr_accessor cited_text: String

              attr_accessor document_index: Integer

              attr_accessor document_title: String?

              attr_accessor end_page_number: Integer

              attr_accessor start_page_number: Integer

              attr_accessor type: :page_location

              def initialize: (
                cited_text: String,
                document_index: Integer,
                document_title: String?,
                end_page_number: Integer,
                start_page_number: Integer,
                ?type: :page_location
              ) -> void
            end

            type content_block_location =
              {
                cited_text: String,
                document_index: Integer,
                document_title: String?,
                end_block_index: Integer,
                start_block_index: Integer,
                type: :content_block_location
              }

            class ContentBlockLocation < Sam::Internal::Type::BaseModel
              attr_accessor cited_text: String

              attr_accessor document_index: Integer

              attr_accessor document_title: String?

              attr_accessor end_block_index: Integer

              attr_accessor start_block_index: Integer

              attr_accessor type: :content_block_location

              def initialize: (
                cited_text: String,
                document_index: Integer,
                document_title: String?,
                end_block_index: Integer,
                start_block_index: Integer,
                ?type: :content_block_location
              ) -> void
            end

            def self?.variants: -> ::Array[Sam::Models::MessagesBetaTrueCreateResponse::Content::Text::citation]
          end
        end

        type tool_use =
          { id: String, input: top, name: String, type: :tool_use }

        class ToolUse < Sam::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor input: top

          attr_accessor name: String

          attr_accessor type: :tool_use

          def initialize: (
            id: String,
            input: top,
            name: String,
            ?type: :tool_use
          ) -> void
        end

        type thinking = { signature: String, thinking: String, type: :thinking }

        class Thinking < Sam::Internal::Type::BaseModel
          attr_accessor signature: String

          attr_accessor thinking: String

          attr_accessor type: :thinking

          def initialize: (
            signature: String,
            thinking: String,
            ?type: :thinking
          ) -> void
        end

        type redacted_thinking = { data: String, type: :redacted_thinking }

        class RedactedThinking < Sam::Internal::Type::BaseModel
          attr_accessor data: String

          attr_accessor type: :redacted_thinking

          def initialize: (data: String, ?type: :redacted_thinking) -> void
        end

        def self?.variants: -> ::Array[Sam::Models::MessagesBetaTrueCreateResponse::content]
      end

      type stop_reason = :end_turn | :max_tokens | :stop_sequence | :tool_use

      module StopReason
        extend Sam::Internal::Type::Enum

        END_TURN: :end_turn
        MAX_TOKENS: :max_tokens
        STOP_SEQUENCE: :stop_sequence
        TOOL_USE: :tool_use

        def self?.values: -> ::Array[Sam::Models::MessagesBetaTrueCreateResponse::stop_reason]
      end

      type usage =
        {
          cache_creation_input_tokens: Integer?,
          cache_read_input_tokens: Integer?,
          input_tokens: Integer,
          output_tokens: Integer
        }

      class Usage < Sam::Internal::Type::BaseModel
        attr_accessor cache_creation_input_tokens: Integer?

        attr_accessor cache_read_input_tokens: Integer?

        attr_accessor input_tokens: Integer

        attr_accessor output_tokens: Integer

        def initialize: (
          cache_creation_input_tokens: Integer?,
          cache_read_input_tokens: Integer?,
          input_tokens: Integer,
          output_tokens: Integer
        ) -> void
      end
    end
  end
end
