module Sam
  module Models
    type model_retrieve_beta_params =
      { anthropic_version: String, x_api_key: String } & Sam::request_parameters

    class ModelRetrieveBetaParams < Sam::BaseModel
      extend Sam::RequestParameters::Converter
      include Sam::RequestParameters

      attr_reader anthropic_version: String?

      def anthropic_version=: (String) -> String

      attr_reader x_api_key: String?

      def x_api_key=: (String) -> String

      def initialize: (
        ?anthropic_version: String,
        ?x_api_key: String,
        ?request_options: Sam::request_opts
      ) -> void

      def to_hash: -> Sam::Models::model_retrieve_beta_params
    end
  end
end
