module Sam
  module Models
    type model_retrieve_beta_response =
      { id: String, created_at: Time, display_name: String, type: :model }

    class ModelRetrieveBetaResponse < Sam::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor created_at: Time

      attr_accessor display_name: String

      attr_accessor type: :model

      def initialize: (
        id: String,
        created_at: Time,
        display_name: String,
        ?type: :model
      ) -> void

      def to_hash: -> Sam::Models::model_retrieve_beta_response
    end
  end
end
