module Sam
  module Models
    type model_retrieve_params =
      { anthropic_version: String, x_api_key: String }
      & Sam::Internal::Type::request_parameters

    class ModelRetrieveParams < Sam::BaseModel
      extend Sam::Internal::Type::RequestParameters::Converter
      include Sam::Internal::Type::RequestParameters

      attr_reader anthropic_version: String?

      def anthropic_version=: (String) -> String

      attr_reader x_api_key: String?

      def x_api_key=: (String) -> String

      def initialize: (
        ?anthropic_version: String,
        ?x_api_key: String,
        ?request_options: Sam::request_opts
      ) -> void

      def to_hash: -> Sam::Models::model_retrieve_params
    end
  end
end
