module Sam
  module Models
    type order =
      {
        id: Integer,
        complete: bool,
        pet_id: Integer,
        quantity: Integer,
        ship_date: Time,
        status: Sam::Models::Order::status
      }

    class Order < Sam::BaseModel
      attr_reader id: Integer?

      def id=: (Integer) -> void

      attr_reader complete: bool?

      def complete=: (bool) -> void

      attr_reader pet_id: Integer?

      def pet_id=: (Integer) -> void

      attr_reader quantity: Integer?

      def quantity=: (Integer) -> void

      attr_reader ship_date: Time?

      def ship_date=: (Time) -> void

      attr_reader status: Sam::Models::Order::status?

      def status=: (Sam::Models::Order::status) -> void

      def initialize:
        (
          id: Integer,
          complete: bool,
          pet_id: Integer,
          quantity: Integer,
          ship_date: Time,
          status: Sam::Models::Order::status
        ) -> void
        | (?Sam::Models::order | Sam::BaseModel data) -> void

      def to_hash: -> Sam::Models::order

      type status = :placed | :approved | :delivered

      class Status < Sam::Enum
        PLACED: :placed
        APPROVED: :approved
        DELIVERED: :delivered

        def self.values: -> ::Array[Sam::Models::Order::status]
      end
    end
  end
end
