module Sam
  module Models
    type user_login_params =
      { password: String, username: String } & Sam::request_parameters

    class UserLoginParams < Sam::BaseModel
      extend Sam::RequestParameters::Converter
      include Sam::RequestParameters

      attr_reader password: String?

      def password=: (String) -> void

      attr_reader username: String?

      def username=: (String) -> void

      def initialize:
        (
          password: String,
          username: String,
          request_options: Sam::request_opts
        ) -> void
        | (?Sam::Models::user_login_params | Sam::BaseModel data) -> void

      def to_hash: -> Sam::Models::user_login_params
    end
  end
end
