module Sam
  module Models
    type user_api =
      {
        id: Integer,
        email: String,
        first_name: String,
        last_name: String,
        password: String,
        phone: String,
        username: String,
        user_status: Integer
      }

    class UserAPI < Sam::BaseModel
      attr_reader id: Integer?

      def id=: (Integer) -> void

      attr_reader email: String?

      def email=: (String) -> void

      attr_reader first_name: String?

      def first_name=: (String) -> void

      attr_reader last_name: String?

      def last_name=: (String) -> void

      attr_reader password: String?

      def password=: (String) -> void

      attr_reader phone: String?

      def phone=: (String) -> void

      attr_reader username: String?

      def username=: (String) -> void

      attr_reader user_status: Integer?

      def user_status=: (Integer) -> void

      def initialize:
        (
          id: Integer,
          email: String,
          first_name: String,
          last_name: String,
          password: String,
          phone: String,
          username: String,
          user_status: Integer
        ) -> void
        | (?Sam::Models::user_api | Sam::BaseModel data) -> void

      def to_hash: -> Sam::Models::user_api
    end
  end
end
