module Sam
  module Models
    type user_logout_params = {  } & Sam::request_parameters

    class UserLogoutParams < Sam::BaseModel
      extend Sam::RequestParameters::Converter
      include Sam::RequestParameters

      def initialize:
        (request_options: Sam::request_opts) -> void
        | (?Sam::Models::user_logout_params | Sam::BaseModel data) -> void

      def to_hash: -> Sam::Models::user_logout_params
    end
  end
end
