module Sam
  module Models
    module Messages
      module Batches
        type beta_true_delete_params =
          {
            anthropic_beta: ::Array[String],
            anthropic_version: String,
            x_api_key: String
          }
          & Sam::request_parameters

        class BetaTrueDeleteParams < Sam::BaseModel
          extend Sam::RequestParameters::Converter
          include Sam::RequestParameters

          attr_reader anthropic_beta: ::Array[String]?

          def anthropic_beta=: (::Array[String]) -> ::Array[String]

          attr_reader anthropic_version: String?

          def anthropic_version=: (String) -> String

          attr_reader x_api_key: String?

          def x_api_key=: (String) -> String

          def initialize:
            (
              anthropic_beta: ::Array[String],
              anthropic_version: String,
              x_api_key: String,
              request_options: Sam::request_opts
            ) -> void
            | (
              ?Sam::Models::Messages::Batches::beta_true_delete_params
              | Sam::BaseModel data
            ) -> void

          def to_hash: -> Sam::Models::Messages::Batches::beta_true_delete_params
        end
      end
    end
  end
end
