module Sam
  module Resources
    class Messages
      class BatchesBetaTrue
        def create: (
          requests: ::Array[Sam::Messages::BatchesBetaTrueCreateParams::Request],
          ?anthropic_beta: ::Array[String],
          ?anthropic_version: String,
          ?x_api_key: String,
          ?request_options: Sam::request_opts
        ) -> Sam::Models::Messages::BatchesBetaTrueCreateResponse

        def list: (
          ?after_id: String,
          ?before_id: String,
          ?limit: Integer,
          ?anthropic_beta: ::Array[String],
          ?anthropic_version: String,
          ?x_api_key: String,
          ?request_options: Sam::request_opts
        ) -> Sam::Models::Messages::BatchesBetaTrueListResponse

        def initialize: (client: Sam::Client) -> void
      end
    end
  end
end
