# typed: strong

module Sam
  module Models
    class MessagesBetaTrueCreateResponse < Sam::BaseModel
      # Unique object identifier.
      #
      #   The format and length of IDs may change over time.
      sig { returns(String) }
      def id
      end

      sig { params(_: String).returns(String) }
      def id=(_)
      end

      # Content generated by the model.
      #
      #   This is an array of content blocks, each of which has a `type` that determines
      #   its shape.
      #
      #   Example:
      #
      #   ```json
      #   [{ "type": "text", "text": "Hi, I'm Claude." }]
      #   ```
      #
      #   If the request input `messages` ended with an `assistant` turn, then the
      #   response `content` will continue directly from that last turn. You can use this
      #   to constrain the model's output.
      #
      #   For example, if the input `messages` were:
      #
      #   ```json
      #   [
      #     {
      #       "role": "user",
      #       "content": "What's the Greek name for Sun? (A) Sol (B) Helios (C) Sun"
      #     },
      #     { "role": "assistant", "content": "The best answer is (" }
      #   ]
      #   ```
      #
      #   Then the response `content` might be:
      #
      #   ```json
      #   [{ "type": "text", "text": "B)" }]
      #   ```
      sig do
        returns(
          T::Array[
          T.any(
            Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseTextBlock,
            Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseToolUseBlock,
            Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseThinkingBlock,
            Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseRedactedThinkingBlock
          )
          ]
        )
      end
      def content
      end

      sig do
        params(
          _: T::Array[
          T.any(
            Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseTextBlock,
            Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseToolUseBlock,
            Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseThinkingBlock,
            Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseRedactedThinkingBlock
          )
          ]
        )
          .returns(
            T::Array[
            T.any(
              Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseTextBlock,
              Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseToolUseBlock,
              Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseThinkingBlock,
              Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseRedactedThinkingBlock
            )
            ]
          )
      end
      def content=(_)
      end

      # The model that handled the request.
      sig { returns(String) }
      def model
      end

      sig { params(_: String).returns(String) }
      def model=(_)
      end

      # Conversational role of the generated message.
      #
      #   This will always be `"assistant"`.
      sig { returns(Symbol) }
      def role
      end

      sig { params(_: Symbol).returns(Symbol) }
      def role=(_)
      end

      # The reason that we stopped.
      #
      #   This may be one the following values:
      #
      #   - `"end_turn"`: the model reached a natural stopping point
      #   - `"max_tokens"`: we exceeded the requested `max_tokens` or the model's maximum
      #   - `"stop_sequence"`: one of your provided custom `stop_sequences` was generated
      #   - `"tool_use"`: the model invoked one or more tools
      #
      #   In non-streaming mode this value is always non-null. In streaming mode, it is
      #   null in the `message_start` event and non-null otherwise.
      sig { returns(T.nilable(Symbol)) }
      def stop_reason
      end

      sig { params(_: T.nilable(Symbol)).returns(T.nilable(Symbol)) }
      def stop_reason=(_)
      end

      # Which custom stop sequence was generated, if any.
      #
      #   This value will be a non-null string if one of your custom stop sequences was
      #   generated.
      sig { returns(T.nilable(String)) }
      def stop_sequence
      end

      sig { params(_: T.nilable(String)).returns(T.nilable(String)) }
      def stop_sequence=(_)
      end

      # Object type.
      #
      #   For Messages, this is always `"message"`.
      sig { returns(Symbol) }
      def type
      end

      sig { params(_: Symbol).returns(Symbol) }
      def type=(_)
      end

      # Billing and rate-limit usage.
      #
      #   Anthropic's API bills and rate-limits by token counts, as tokens represent the
      #   underlying cost to our systems.
      #
      #   Under the hood, the API transforms requests into a format suitable for the
      #   model. The model's output then goes through a parsing stage before becoming an
      #   API response. As a result, the token counts in `usage` will not match one-to-one
      #   with the exact visible content of an API request or response.
      #
      #   For example, `output_tokens` will be non-zero, even for an empty string response
      #   from Claude.
      #
      #   Total input tokens in a request is the summation of `input_tokens`,
      #   `cache_creation_input_tokens`, and `cache_read_input_tokens`.
      sig { returns(Sam::Models::MessagesBetaTrueCreateResponse::Usage) }
      def usage
      end

      sig do
        params(_: Sam::Models::MessagesBetaTrueCreateResponse::Usage)
          .returns(Sam::Models::MessagesBetaTrueCreateResponse::Usage)
      end
      def usage=(_)
      end

      sig do
        params(
          id: String,
          content: T::Array[
          T.any(
            Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseTextBlock,
            Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseToolUseBlock,
            Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseThinkingBlock,
            Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseRedactedThinkingBlock
          )
          ],
          model: String,
          stop_reason: T.nilable(Symbol),
          stop_sequence: T.nilable(String),
          usage: Sam::Models::MessagesBetaTrueCreateResponse::Usage,
          role: Symbol,
          type: Symbol
        )
          .returns(T.attached_class)
      end
      def self.new(id:, content:, model:, stop_reason:, stop_sequence:, usage:, role: :assistant, type: :message)
      end

      sig do
        override
          .returns(
            {
              id: String,
              content: T::Array[
              T.any(
                Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseTextBlock,
                Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseToolUseBlock,
                Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseThinkingBlock,
                Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseRedactedThinkingBlock
              )
              ],
              model: String,
              role: Symbol,
              stop_reason: T.nilable(Symbol),
              stop_sequence: T.nilable(String),
              type: Symbol,
              usage: Sam::Models::MessagesBetaTrueCreateResponse::Usage
            }
          )
      end
      def to_hash
      end

      class Content < Sam::Union
        abstract!

        class BetaResponseTextBlock < Sam::BaseModel
          # Citations supporting the text block.
          #
          #   The type of citation returned will depend on the type of document being cited.
          #   Citing a PDF results in `page_location`, plain text results in `char_location`,
          #   and content document results in `content_block_location`.
          sig do
            returns(
              T.nilable(
                T::Array[
                T.any(
                  Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseTextBlock::Citation::BetaResponseCharLocationCitation,
                  Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseTextBlock::Citation::BetaResponsePageLocationCitation,
                  Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseTextBlock::Citation::BetaResponseContentBlockLocationCitation
                )
                ]
              )
            )
          end
          def citations
          end

          sig do
            params(
              _: T.nilable(
                T::Array[
                T.any(
                  Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseTextBlock::Citation::BetaResponseCharLocationCitation,
                  Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseTextBlock::Citation::BetaResponsePageLocationCitation,
                  Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseTextBlock::Citation::BetaResponseContentBlockLocationCitation
                )
                ]
              )
            )
              .returns(
                T.nilable(
                  T::Array[
                  T.any(
                    Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseTextBlock::Citation::BetaResponseCharLocationCitation,
                    Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseTextBlock::Citation::BetaResponsePageLocationCitation,
                    Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseTextBlock::Citation::BetaResponseContentBlockLocationCitation
                  )
                  ]
                )
              )
          end
          def citations=(_)
          end

          sig { returns(String) }
          def text
          end

          sig { params(_: String).returns(String) }
          def text=(_)
          end

          sig { returns(Symbol) }
          def type
          end

          sig { params(_: Symbol).returns(Symbol) }
          def type=(_)
          end

          sig do
            params(
              citations: T.nilable(
                T::Array[
                T.any(
                  Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseTextBlock::Citation::BetaResponseCharLocationCitation,
                  Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseTextBlock::Citation::BetaResponsePageLocationCitation,
                  Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseTextBlock::Citation::BetaResponseContentBlockLocationCitation
                )
                ]
              ),
              text: String,
              type: Symbol
            )
              .returns(T.attached_class)
          end
          def self.new(citations:, text:, type: :text)
          end

          sig do
            override
              .returns(
                {
                  citations: T.nilable(
                    T::Array[
                    T.any(
                      Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseTextBlock::Citation::BetaResponseCharLocationCitation,
                      Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseTextBlock::Citation::BetaResponsePageLocationCitation,
                      Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseTextBlock::Citation::BetaResponseContentBlockLocationCitation
                    )
                    ]
                  ),
                  text: String,
                  type: Symbol
                }
              )
          end
          def to_hash
          end

          class Citation < Sam::Union
            abstract!

            class BetaResponseCharLocationCitation < Sam::BaseModel
              sig { returns(String) }
              def cited_text
              end

              sig { params(_: String).returns(String) }
              def cited_text=(_)
              end

              sig { returns(Integer) }
              def document_index
              end

              sig { params(_: Integer).returns(Integer) }
              def document_index=(_)
              end

              sig { returns(T.nilable(String)) }
              def document_title
              end

              sig { params(_: T.nilable(String)).returns(T.nilable(String)) }
              def document_title=(_)
              end

              sig { returns(Integer) }
              def end_char_index
              end

              sig { params(_: Integer).returns(Integer) }
              def end_char_index=(_)
              end

              sig { returns(Integer) }
              def start_char_index
              end

              sig { params(_: Integer).returns(Integer) }
              def start_char_index=(_)
              end

              sig { returns(Symbol) }
              def type
              end

              sig { params(_: Symbol).returns(Symbol) }
              def type=(_)
              end

              sig do
                params(
                  cited_text: String,
                  document_index: Integer,
                  document_title: T.nilable(String),
                  end_char_index: Integer,
                  start_char_index: Integer,
                  type: Symbol
                )
                  .returns(T.attached_class)
              end
              def self.new(cited_text:, document_index:, document_title:, end_char_index:, start_char_index:, type: :char_location)
              end

              sig do
                override
                  .returns(
                    {
                      cited_text: String,
                      document_index: Integer,
                      document_title: T.nilable(String),
                      end_char_index: Integer,
                      start_char_index: Integer,
                      type: Symbol
                    }
                  )
              end
              def to_hash
              end
            end

            class BetaResponsePageLocationCitation < Sam::BaseModel
              sig { returns(String) }
              def cited_text
              end

              sig { params(_: String).returns(String) }
              def cited_text=(_)
              end

              sig { returns(Integer) }
              def document_index
              end

              sig { params(_: Integer).returns(Integer) }
              def document_index=(_)
              end

              sig { returns(T.nilable(String)) }
              def document_title
              end

              sig { params(_: T.nilable(String)).returns(T.nilable(String)) }
              def document_title=(_)
              end

              sig { returns(Integer) }
              def end_page_number
              end

              sig { params(_: Integer).returns(Integer) }
              def end_page_number=(_)
              end

              sig { returns(Integer) }
              def start_page_number
              end

              sig { params(_: Integer).returns(Integer) }
              def start_page_number=(_)
              end

              sig { returns(Symbol) }
              def type
              end

              sig { params(_: Symbol).returns(Symbol) }
              def type=(_)
              end

              sig do
                params(
                  cited_text: String,
                  document_index: Integer,
                  document_title: T.nilable(String),
                  end_page_number: Integer,
                  start_page_number: Integer,
                  type: Symbol
                )
                  .returns(T.attached_class)
              end
              def self.new(cited_text:, document_index:, document_title:, end_page_number:, start_page_number:, type: :page_location)
              end

              sig do
                override
                  .returns(
                    {
                      cited_text: String,
                      document_index: Integer,
                      document_title: T.nilable(String),
                      end_page_number: Integer,
                      start_page_number: Integer,
                      type: Symbol
                    }
                  )
              end
              def to_hash
              end
            end

            class BetaResponseContentBlockLocationCitation < Sam::BaseModel
              sig { returns(String) }
              def cited_text
              end

              sig { params(_: String).returns(String) }
              def cited_text=(_)
              end

              sig { returns(Integer) }
              def document_index
              end

              sig { params(_: Integer).returns(Integer) }
              def document_index=(_)
              end

              sig { returns(T.nilable(String)) }
              def document_title
              end

              sig { params(_: T.nilable(String)).returns(T.nilable(String)) }
              def document_title=(_)
              end

              sig { returns(Integer) }
              def end_block_index
              end

              sig { params(_: Integer).returns(Integer) }
              def end_block_index=(_)
              end

              sig { returns(Integer) }
              def start_block_index
              end

              sig { params(_: Integer).returns(Integer) }
              def start_block_index=(_)
              end

              sig { returns(Symbol) }
              def type
              end

              sig { params(_: Symbol).returns(Symbol) }
              def type=(_)
              end

              sig do
                params(
                  cited_text: String,
                  document_index: Integer,
                  document_title: T.nilable(String),
                  end_block_index: Integer,
                  start_block_index: Integer,
                  type: Symbol
                )
                  .returns(T.attached_class)
              end
              def self.new(
                cited_text:,
                document_index:,
                document_title:,
                end_block_index:,
                start_block_index:,
                type: :content_block_location
              )
              end

              sig do
                override
                  .returns(
                    {
                      cited_text: String,
                      document_index: Integer,
                      document_title: T.nilable(String),
                      end_block_index: Integer,
                      start_block_index: Integer,
                      type: Symbol
                    }
                  )
              end
              def to_hash
              end
            end

            class << self
              sig do
                override
                  .returns(
                    [Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseTextBlock::Citation::BetaResponseCharLocationCitation, Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseTextBlock::Citation::BetaResponsePageLocationCitation, Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseTextBlock::Citation::BetaResponseContentBlockLocationCitation]
                  )
              end
              def variants
              end
            end
          end
        end

        class BetaResponseToolUseBlock < Sam::BaseModel
          sig { returns(String) }
          def id
          end

          sig { params(_: String).returns(String) }
          def id=(_)
          end

          sig { returns(T.anything) }
          def input
          end

          sig { params(_: T.anything).returns(T.anything) }
          def input=(_)
          end

          sig { returns(String) }
          def name
          end

          sig { params(_: String).returns(String) }
          def name=(_)
          end

          sig { returns(Symbol) }
          def type
          end

          sig { params(_: Symbol).returns(Symbol) }
          def type=(_)
          end

          sig { params(id: String, input: T.anything, name: String, type: Symbol).returns(T.attached_class) }
          def self.new(id:, input:, name:, type: :tool_use)
          end

          sig { override.returns({id: String, input: T.anything, name: String, type: Symbol}) }
          def to_hash
          end
        end

        class BetaResponseThinkingBlock < Sam::BaseModel
          sig { returns(String) }
          def signature
          end

          sig { params(_: String).returns(String) }
          def signature=(_)
          end

          sig { returns(String) }
          def thinking
          end

          sig { params(_: String).returns(String) }
          def thinking=(_)
          end

          sig { returns(Symbol) }
          def type
          end

          sig { params(_: Symbol).returns(Symbol) }
          def type=(_)
          end

          sig { params(signature: String, thinking: String, type: Symbol).returns(T.attached_class) }
          def self.new(signature:, thinking:, type: :thinking)
          end

          sig { override.returns({signature: String, thinking: String, type: Symbol}) }
          def to_hash
          end
        end

        class BetaResponseRedactedThinkingBlock < Sam::BaseModel
          sig { returns(String) }
          def data
          end

          sig { params(_: String).returns(String) }
          def data=(_)
          end

          sig { returns(Symbol) }
          def type
          end

          sig { params(_: Symbol).returns(Symbol) }
          def type=(_)
          end

          sig { params(data: String, type: Symbol).returns(T.attached_class) }
          def self.new(data:, type: :redacted_thinking)
          end

          sig { override.returns({data: String, type: Symbol}) }
          def to_hash
          end
        end

        class << self
          sig do
            override
              .returns(
                [Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseTextBlock, Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseToolUseBlock, Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseThinkingBlock, Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseRedactedThinkingBlock]
              )
          end
          def variants
          end
        end
      end

      # The reason that we stopped.
      #
      #   This may be one the following values:
      #
      #   - `"end_turn"`: the model reached a natural stopping point
      #   - `"max_tokens"`: we exceeded the requested `max_tokens` or the model's maximum
      #   - `"stop_sequence"`: one of your provided custom `stop_sequences` was generated
      #   - `"tool_use"`: the model invoked one or more tools
      #
      #   In non-streaming mode this value is always non-null. In streaming mode, it is
      #   null in the `message_start` event and non-null otherwise.
      class StopReason < Sam::Enum
        abstract!

        END_TURN = T.let(:end_turn, T.nilable(Symbol))
        MAX_TOKENS = T.let(:max_tokens, T.nilable(Symbol))
        STOP_SEQUENCE = T.let(:stop_sequence, T.nilable(Symbol))
        TOOL_USE = T.let(:tool_use, T.nilable(Symbol))

        class << self
          sig { override.returns(T::Array[Symbol]) }
          def values
          end
        end
      end

      class Usage < Sam::BaseModel
        # The number of input tokens used to create the cache entry.
        sig { returns(T.nilable(Integer)) }
        def cache_creation_input_tokens
        end

        sig { params(_: T.nilable(Integer)).returns(T.nilable(Integer)) }
        def cache_creation_input_tokens=(_)
        end

        # The number of input tokens read from the cache.
        sig { returns(T.nilable(Integer)) }
        def cache_read_input_tokens
        end

        sig { params(_: T.nilable(Integer)).returns(T.nilable(Integer)) }
        def cache_read_input_tokens=(_)
        end

        # The number of input tokens which were used.
        sig { returns(Integer) }
        def input_tokens
        end

        sig { params(_: Integer).returns(Integer) }
        def input_tokens=(_)
        end

        # The number of output tokens which were used.
        sig { returns(Integer) }
        def output_tokens
        end

        sig { params(_: Integer).returns(Integer) }
        def output_tokens=(_)
        end

        # Billing and rate-limit usage.
        #
        #   Anthropic's API bills and rate-limits by token counts, as tokens represent the
        #   underlying cost to our systems.
        #
        #   Under the hood, the API transforms requests into a format suitable for the
        #   model. The model's output then goes through a parsing stage before becoming an
        #   API response. As a result, the token counts in `usage` will not match one-to-one
        #   with the exact visible content of an API request or response.
        #
        #   For example, `output_tokens` will be non-zero, even for an empty string response
        #   from Claude.
        #
        #   Total input tokens in a request is the summation of `input_tokens`,
        #   `cache_creation_input_tokens`, and `cache_read_input_tokens`.
        sig do
          params(
            cache_creation_input_tokens: T.nilable(Integer),
            cache_read_input_tokens: T.nilable(Integer),
            input_tokens: Integer,
            output_tokens: Integer
          )
            .returns(T.attached_class)
        end
        def self.new(cache_creation_input_tokens:, cache_read_input_tokens:, input_tokens:, output_tokens:)
        end

        sig do
          override
            .returns(
              {
                cache_creation_input_tokens: T.nilable(Integer),
                cache_read_input_tokens: T.nilable(Integer),
                input_tokens: Integer,
                output_tokens: Integer
              }
            )
        end
        def to_hash
        end
      end
    end
  end
end
