module Sam
  class Unknown = Sam::Internal::Type::Unknown

  class BooleanModel = Sam::Internal::Type::BooleanModel

  module Enum = Sam::Internal::Type::Enum

  module Union = Sam::Internal::Type::Union

  class ArrayOf = Sam::Internal::Type::ArrayOf

  class HashOf = Sam::Internal::Type::HashOf

  class BaseModel = Sam::Internal::Type::BaseModel

  type request_parameters = Sam::Internal::Type::request_parameters

  module RequestParameters = Sam::Internal::Type::RequestParameters
end
