module Sam
  module Errors
    class Error < StandardError
      attr_accessor cause: StandardError?
    end

    class ConversionError < Sam::Errors::Error
    end

    class APIError < Sam::Errors::Error
      attr_accessor url: URI::Generic

      attr_accessor status: Integer?

      attr_accessor body: top?

      def initialize: (
        url: URI::Generic,
        ?status: Integer?,
        ?body: Object?,
        ?request: nil,
        ?response: nil,
        ?message: String?
      ) -> void
    end

    class APIConnectionError < Sam::Errors::APIError
      def initialize: (
        url: URI::Generic,
        ?status: nil,
        ?body: nil,
        ?request: nil,
        ?response: nil,
        ?message: String?
      ) -> void
    end

    class APITimeoutError < Sam::Errors::APIConnectionError
      def initialize: (
        url: URI::Generic,
        ?status: nil,
        ?body: nil,
        ?request: nil,
        ?response: nil,
        ?message: String?
      ) -> void
    end

    class APIStatusError < Sam::Errors::APIError
      def self.for: (
        url: URI::Generic,
        status: Integer,
        body: Object?,
        request: nil,
        response: nil,
        ?message: String?
      ) -> instance

      def initialize: (
        url: URI::Generic,
        status: Integer,
        body: Object?,
        request: nil,
        response: nil,
        ?message: String?
      ) -> void
    end

    class BadRequestError < Sam::Errors::APIStatusError
      HTTP_STATUS: 400
    end

    class AuthenticationError < Sam::Errors::APIStatusError
      HTTP_STATUS: 401
    end

    class PermissionDeniedError < Sam::Errors::APIStatusError
      HTTP_STATUS: 403
    end

    class NotFoundError < Sam::Errors::APIStatusError
      HTTP_STATUS: 404
    end

    class ConflictError < Sam::Errors::APIStatusError
      HTTP_STATUS: 409
    end

    class UnprocessableEntityError < Sam::Errors::APIStatusError
      HTTP_STATUS: 422
    end

    class RateLimitError < Sam::Errors::APIStatusError
      HTTP_STATUS: 429
    end

    class InternalServerError < Sam::Errors::APIStatusError
      HTTP_STATUS: Range[Integer]
    end
  end

  class Error = Sam::Errors::Error

  class ConversionError = Sam::Errors::ConversionError

  class APIError = Sam::Errors::APIError

  class APIStatusError = Sam::Errors::APIStatusError

  class APIConnectionError = Sam::Errors::APIConnectionError

  class APITimeoutError = Sam::Errors::APITimeoutError

  class BadRequestError = Sam::Errors::BadRequestError

  class AuthenticationError = Sam::Errors::AuthenticationError

  class PermissionDeniedError = Sam::Errors::PermissionDeniedError

  class NotFoundError = Sam::Errors::NotFoundError

  class ConflictError = Sam::Errors::ConflictError

  class UnprocessableEntityError = Sam::Errors::UnprocessableEntityError

  class RateLimitError = Sam::Errors::RateLimitError

  class InternalServerError = Sam::Errors::InternalServerError
end
