module Sam
  class JsonLStream[Elem]
    include Sam::BaseStream[top, Elem]

    private def iterator: -> Enumerable[Elem]

    def initialize: (
      model: Class | Sam::Converter,
      url: URI::Generic,
      status: Integer,
      response: top,
      messages: Enumerable[top]
    ) -> void
  end
end
