module Sam
  class Unknown = Sam::Type::Unknown

  class BooleanModel = Sam::Type::BooleanModel

  module Enum = Sam::Type::Enum

  module Union = Sam::Type::Union

  class ArrayOf = Sam::Type::ArrayOf

  class HashOf = Sam::Type::HashOf

  class BaseModel = Sam::Type::BaseModel

  type request_parameters = Sam::Type::request_parameters

  module RequestParameters = Sam::Type::RequestParameters

  module Type
  end
end
