# frozen_string_literal: true

module Sam
  module Models
    # @see Sam::Resources::MessagesBetaTrue#create
    class MessagesBetaTrueCreateResponse < Sam::Internal::Type::BaseModel
      # @!attribute id
      #   Unique object identifier.
      #
      #   The format and length of IDs may change over time.
      #
      #   @return [String]
      required :id, String

      # @!attribute content
      #   Content generated by the model.
      #
      #   This is an array of content blocks, each of which has a `type` that determines
      #   its shape.
      #
      #   Example:
      #
      #   ```json
      #   [{ "type": "text", "text": "Hi, I'm Claude." }]
      #   ```
      #
      #   If the request input `messages` ended with an `assistant` turn, then the
      #   response `content` will continue directly from that last turn. You can use this
      #   to constrain the model's output.
      #
      #   For example, if the input `messages` were:
      #
      #   ```json
      #   [
      #     {
      #       "role": "user",
      #       "content": "What's the Greek name for Sun? (A) Sol (B) Helios (C) Sun"
      #     },
      #     { "role": "assistant", "content": "The best answer is (" }
      #   ]
      #   ```
      #
      #   Then the response `content` might be:
      #
      #   ```json
      #   [{ "type": "text", "text": "B)" }]
      #   ```
      #
      #   @return [Array<Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseTextBlock, Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseToolUseBlock, Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseThinkingBlock, Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseRedactedThinkingBlock>]
      required :content,
               -> { Sam::Internal::Type::ArrayOf[union: Sam::Models::MessagesBetaTrueCreateResponse::Content] }

      # @!attribute model
      #   The model that handled the request.
      #
      #   @return [String]
      required :model, String

      # @!attribute role
      #   Conversational role of the generated message.
      #
      #   This will always be `"assistant"`.
      #
      #   @return [Symbol, :assistant]
      required :role, const: :assistant

      # @!attribute stop_reason
      #   The reason that we stopped.
      #
      #   This may be one the following values:
      #
      #   - `"end_turn"`: the model reached a natural stopping point
      #   - `"max_tokens"`: we exceeded the requested `max_tokens` or the model's maximum
      #   - `"stop_sequence"`: one of your provided custom `stop_sequences` was generated
      #   - `"tool_use"`: the model invoked one or more tools
      #
      #   In non-streaming mode this value is always non-null. In streaming mode, it is
      #   null in the `message_start` event and non-null otherwise.
      #
      #   @return [Symbol, Sam::Models::MessagesBetaTrueCreateResponse::StopReason, nil]
      required :stop_reason, enum: -> { Sam::Models::MessagesBetaTrueCreateResponse::StopReason }, nil?: true

      # @!attribute stop_sequence
      #   Which custom stop sequence was generated, if any.
      #
      #   This value will be a non-null string if one of your custom stop sequences was
      #   generated.
      #
      #   @return [String, nil]
      required :stop_sequence, String, nil?: true

      # @!attribute type
      #   Object type.
      #
      #   For Messages, this is always `"message"`.
      #
      #   @return [Symbol, :message]
      required :type, const: :message

      # @!attribute usage
      #   Billing and rate-limit usage.
      #
      #   Anthropic's API bills and rate-limits by token counts, as tokens represent the
      #   underlying cost to our systems.
      #
      #   Under the hood, the API transforms requests into a format suitable for the
      #   model. The model's output then goes through a parsing stage before becoming an
      #   API response. As a result, the token counts in `usage` will not match one-to-one
      #   with the exact visible content of an API request or response.
      #
      #   For example, `output_tokens` will be non-zero, even for an empty string response
      #   from Claude.
      #
      #   Total input tokens in a request is the summation of `input_tokens`,
      #   `cache_creation_input_tokens`, and `cache_read_input_tokens`.
      #
      #   @return [Sam::Models::MessagesBetaTrueCreateResponse::Usage]
      required :usage, -> { Sam::Models::MessagesBetaTrueCreateResponse::Usage }

      # @!method initialize(id:, content:, model:, stop_reason:, stop_sequence:, usage:, role: :assistant, type: :message)
      #   @param id [String]
      #   @param content [Array<Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseTextBlock, Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseToolUseBlock, Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseThinkingBlock, Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseRedactedThinkingBlock>]
      #   @param model [String]
      #   @param stop_reason [Symbol, Sam::Models::MessagesBetaTrueCreateResponse::StopReason, nil]
      #   @param stop_sequence [String, nil]
      #   @param usage [Sam::Models::MessagesBetaTrueCreateResponse::Usage]
      #   @param role [Symbol, :assistant]
      #   @param type [Symbol, :message]

      module Content
        extend Sam::Internal::Type::Union

        discriminator :type

        variant :text, -> { Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseTextBlock }

        variant :tool_use, -> { Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseToolUseBlock }

        variant :thinking, -> { Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseThinkingBlock }

        variant :redacted_thinking,
                -> { Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseRedactedThinkingBlock }

        class BetaResponseTextBlock < Sam::Internal::Type::BaseModel
          # @!attribute citations
          #   Citations supporting the text block.
          #
          #   The type of citation returned will depend on the type of document being cited.
          #   Citing a PDF results in `page_location`, plain text results in `char_location`,
          #   and content document results in `content_block_location`.
          #
          #   @return [Array<Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseTextBlock::Citation::BetaResponseCharLocationCitation, Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseTextBlock::Citation::BetaResponsePageLocationCitation, Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseTextBlock::Citation::BetaResponseContentBlockLocationCitation>, nil]
          required :citations,
                   -> { Sam::Internal::Type::ArrayOf[union: Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseTextBlock::Citation] },
                   nil?: true

          # @!attribute text
          #
          #   @return [String]
          required :text, String

          # @!attribute type
          #
          #   @return [Symbol, :text]
          required :type, const: :text

          # @!method initialize(citations:, text:, type: :text)
          #   @param citations [Array<Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseTextBlock::Citation::BetaResponseCharLocationCitation, Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseTextBlock::Citation::BetaResponsePageLocationCitation, Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseTextBlock::Citation::BetaResponseContentBlockLocationCitation>, nil]
          #   @param text [String]
          #   @param type [Symbol, :text]

          module Citation
            extend Sam::Internal::Type::Union

            discriminator :type

            variant :char_location,
                    -> { Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseTextBlock::Citation::BetaResponseCharLocationCitation }

            variant :page_location,
                    -> { Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseTextBlock::Citation::BetaResponsePageLocationCitation }

            variant :content_block_location,
                    -> { Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseTextBlock::Citation::BetaResponseContentBlockLocationCitation }

            class BetaResponseCharLocationCitation < Sam::Internal::Type::BaseModel
              # @!attribute cited_text
              #
              #   @return [String]
              required :cited_text, String

              # @!attribute document_index
              #
              #   @return [Integer]
              required :document_index, Integer

              # @!attribute document_title
              #
              #   @return [String, nil]
              required :document_title, String, nil?: true

              # @!attribute end_char_index
              #
              #   @return [Integer]
              required :end_char_index, Integer

              # @!attribute start_char_index
              #
              #   @return [Integer]
              required :start_char_index, Integer

              # @!attribute type
              #
              #   @return [Symbol, :char_location]
              required :type, const: :char_location

              # @!method initialize(cited_text:, document_index:, document_title:, end_char_index:, start_char_index:, type: :char_location)
              #   @param cited_text [String]
              #   @param document_index [Integer]
              #   @param document_title [String, nil]
              #   @param end_char_index [Integer]
              #   @param start_char_index [Integer]
              #   @param type [Symbol, :char_location]
            end

            class BetaResponsePageLocationCitation < Sam::Internal::Type::BaseModel
              # @!attribute cited_text
              #
              #   @return [String]
              required :cited_text, String

              # @!attribute document_index
              #
              #   @return [Integer]
              required :document_index, Integer

              # @!attribute document_title
              #
              #   @return [String, nil]
              required :document_title, String, nil?: true

              # @!attribute end_page_number
              #
              #   @return [Integer]
              required :end_page_number, Integer

              # @!attribute start_page_number
              #
              #   @return [Integer]
              required :start_page_number, Integer

              # @!attribute type
              #
              #   @return [Symbol, :page_location]
              required :type, const: :page_location

              # @!method initialize(cited_text:, document_index:, document_title:, end_page_number:, start_page_number:, type: :page_location)
              #   @param cited_text [String]
              #   @param document_index [Integer]
              #   @param document_title [String, nil]
              #   @param end_page_number [Integer]
              #   @param start_page_number [Integer]
              #   @param type [Symbol, :page_location]
            end

            class BetaResponseContentBlockLocationCitation < Sam::Internal::Type::BaseModel
              # @!attribute cited_text
              #
              #   @return [String]
              required :cited_text, String

              # @!attribute document_index
              #
              #   @return [Integer]
              required :document_index, Integer

              # @!attribute document_title
              #
              #   @return [String, nil]
              required :document_title, String, nil?: true

              # @!attribute end_block_index
              #
              #   @return [Integer]
              required :end_block_index, Integer

              # @!attribute start_block_index
              #
              #   @return [Integer]
              required :start_block_index, Integer

              # @!attribute type
              #
              #   @return [Symbol, :content_block_location]
              required :type, const: :content_block_location

              # @!method initialize(cited_text:, document_index:, document_title:, end_block_index:, start_block_index:, type: :content_block_location)
              #   @param cited_text [String]
              #   @param document_index [Integer]
              #   @param document_title [String, nil]
              #   @param end_block_index [Integer]
              #   @param start_block_index [Integer]
              #   @param type [Symbol, :content_block_location]
            end

            # @!method self.variants
            #   @return [Array(Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseTextBlock::Citation::BetaResponseCharLocationCitation, Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseTextBlock::Citation::BetaResponsePageLocationCitation, Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseTextBlock::Citation::BetaResponseContentBlockLocationCitation)]
          end
        end

        class BetaResponseToolUseBlock < Sam::Internal::Type::BaseModel
          # @!attribute id
          #
          #   @return [String]
          required :id, String

          # @!attribute input
          #
          #   @return [Object]
          required :input, Sam::Internal::Type::Unknown

          # @!attribute name
          #
          #   @return [String]
          required :name, String

          # @!attribute type
          #
          #   @return [Symbol, :tool_use]
          required :type, const: :tool_use

          # @!method initialize(id:, input:, name:, type: :tool_use)
          #   @param id [String]
          #   @param input [Object]
          #   @param name [String]
          #   @param type [Symbol, :tool_use]
        end

        class BetaResponseThinkingBlock < Sam::Internal::Type::BaseModel
          # @!attribute signature
          #
          #   @return [String]
          required :signature, String

          # @!attribute thinking
          #
          #   @return [String]
          required :thinking, String

          # @!attribute type
          #
          #   @return [Symbol, :thinking]
          required :type, const: :thinking

          # @!method initialize(signature:, thinking:, type: :thinking)
          #   @param signature [String]
          #   @param thinking [String]
          #   @param type [Symbol, :thinking]
        end

        class BetaResponseRedactedThinkingBlock < Sam::Internal::Type::BaseModel
          # @!attribute data
          #
          #   @return [String]
          required :data, String

          # @!attribute type
          #
          #   @return [Symbol, :redacted_thinking]
          required :type, const: :redacted_thinking

          # @!method initialize(data:, type: :redacted_thinking)
          #   @param data [String]
          #   @param type [Symbol, :redacted_thinking]
        end

        # @!method self.variants
        #   @return [Array(Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseTextBlock, Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseToolUseBlock, Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseThinkingBlock, Sam::Models::MessagesBetaTrueCreateResponse::Content::BetaResponseRedactedThinkingBlock)]
      end

      # The reason that we stopped.
      #
      # This may be one the following values:
      #
      # - `"end_turn"`: the model reached a natural stopping point
      # - `"max_tokens"`: we exceeded the requested `max_tokens` or the model's maximum
      # - `"stop_sequence"`: one of your provided custom `stop_sequences` was generated
      # - `"tool_use"`: the model invoked one or more tools
      #
      # In non-streaming mode this value is always non-null. In streaming mode, it is
      # null in the `message_start` event and non-null otherwise.
      #
      # @see Sam::Models::MessagesBetaTrueCreateResponse#stop_reason
      module StopReason
        extend Sam::Internal::Type::Enum

        END_TURN = :end_turn
        MAX_TOKENS = :max_tokens
        STOP_SEQUENCE = :stop_sequence
        TOOL_USE = :tool_use

        # @!method self.values
        #   @return [Array<Symbol>]
      end

      # @see Sam::Models::MessagesBetaTrueCreateResponse#usage
      class Usage < Sam::Internal::Type::BaseModel
        # @!attribute cache_creation_input_tokens
        #   The number of input tokens used to create the cache entry.
        #
        #   @return [Integer, nil]
        required :cache_creation_input_tokens, Integer, nil?: true

        # @!attribute cache_read_input_tokens
        #   The number of input tokens read from the cache.
        #
        #   @return [Integer, nil]
        required :cache_read_input_tokens, Integer, nil?: true

        # @!attribute input_tokens
        #   The number of input tokens which were used.
        #
        #   @return [Integer]
        required :input_tokens, Integer

        # @!attribute output_tokens
        #   The number of output tokens which were used.
        #
        #   @return [Integer]
        required :output_tokens, Integer

        # @!method initialize(cache_creation_input_tokens:, cache_read_input_tokens:, input_tokens:, output_tokens:)
        #   Billing and rate-limit usage.
        #
        #   Anthropic's API bills and rate-limits by token counts, as tokens represent the
        #   underlying cost to our systems.
        #
        #   Under the hood, the API transforms requests into a format suitable for the
        #   model. The model's output then goes through a parsing stage before becoming an
        #   API response. As a result, the token counts in `usage` will not match one-to-one
        #   with the exact visible content of an API request or response.
        #
        #   For example, `output_tokens` will be non-zero, even for an empty string response
        #   from Claude.
        #
        #   Total input tokens in a request is the summation of `input_tokens`,
        #   `cache_creation_input_tokens`, and `cache_read_input_tokens`.
        #
        #   @param cache_creation_input_tokens [Integer, nil]
        #   @param cache_read_input_tokens [Integer, nil]
        #   @param input_tokens [Integer]
        #   @param output_tokens [Integer]
      end
    end
  end
end
